.TH "ccnd/ccnd_stregistry.c" 3 "Tue Apr 1 2014" "Version 0.8.2" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccnd/ccnd_stregistry.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDEFINE_STRATEGY_CLASSES\fP"
.br
.ti -1c
.RI "#define \fBMAX_STRATEGY_CLASSES\fP   ((sizeof(\fBccnd_strategy_classes\fP)/sizeof(\fBccnd_strategy_classes\fP[0]))-1)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBDEFINE_STRATEGY_CLASSES\fP"
.PP
Definition at line 20 of file ccnd_stregistry\&.c\&.
.SS "#define \fBMAX_STRATEGY_CLASSES\fP   ((sizeof(\fBccnd_strategy_classes\fP)/sizeof(\fBccnd_strategy_classes\fP[0]))-1)"
.PP
Definition at line 22 of file ccnd_stregistry\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code\&.
