.TH "ccnd/default_strategy.c" 3 "Tue Apr 1 2014" "Version 0.8.2" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccnd/default_strategy.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBMINE\fP   0x65e272"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCCN_STATESIZECHECK\fP (X_strategy_state, struct strategy_state)"
.br
.ti -1c
.RI "static void \fBadjust_predicted_response\fP (struct \fBccnd_handle\fP *h, struct strategy_state *s, unsigned faceid)"
.br
.RI "\fIAdjust the predicted response associated with a name prefix entry\&. \fP"
.ti -1c
.RI "void \fBccnd_default_strategy_impl\fP (struct \fBccnd_handle\fP *h, struct \fBstrategy_instance\fP *instance, struct \fBccn_strategy\fP *strategy, enum \fBccn_strategy_op\fP op, unsigned faceid)"
.br
.RI "\fIThis implements the default strategy\&. \fP"
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBMINE\fP   0x65e272"
.PP
Definition at line 22 of file default_strategy\&.c\&.
.PP
Referenced by ccnd_default_strategy_impl()\&.
.SH "Function Documentation"
.PP 
.SS "static void \fBadjust_predicted_response\fP (struct \fBccnd_handle\fP *h, struct strategy_state *s, unsignedfaceid)\fC [static]\fP"
.PP
Adjust the predicted response associated with a name prefix entry\&. It is decreased by a small fraction if we get content within our previous predicted value, and increased by a larger fraction if not\&.
.PP
faceid is CCN_NOFACEID if no content arrived, or else tells the arrival face\&. 
.PP
Definition at line 191 of file default_strategy\&.c\&.
.PP
Referenced by ccnd_default_strategy_impl()\&.
.SS "\fBCCN_STATESIZECHECK\fP (X_strategy_state, struct strategy_state)"
.SS "void \fBccnd_default_strategy_impl\fP (struct \fBccnd_handle\fP *h, struct \fBstrategy_instance\fP *instance, struct \fBccn_strategy\fP *strategy, enum \fBccn_strategy_op\fPop, unsignedfaceid)"
.PP
This implements the default strategy\&. 
.PP
Definition at line 41 of file default_strategy\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code\&.
