.TH "strategy_class" 3 "Tue Apr 1 2014" "Version 0.8.2" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
strategy_class \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBid\fP [16]"
.br
.ti -1c
.RI "\fBstrategy_callout_proc\fP \fBcallout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 243 of file ccnd_strategy\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBstrategy_callout_proc\fP \fBstrategy_class::callout\fP"
.PP
Definition at line 245 of file ccnd_strategy\&.h\&.
.PP
Referenced by ccnd_trace_strategy_impl(), remove_strategy_instance(), and strategy_callout()\&.
.SS "char \fBstrategy_class::id\fP[16]"
.PP
Definition at line 244 of file ccnd_strategy\&.h\&.
.PP
Referenced by ccnd_req_strategy(), do_propagate(), and strategy_class_from_id()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code\&.
