Content-Centric Networking in C: lib/ccn_setup_sockaddr_un.c File Reference
ccn_setup_sockaddr_un.c File Reference
Part of the CCNx C Library.
Defines
#define AI_ADDRCONFIG 0 /*IEEE Std 1003.1-2001/Cor 1-2002, item XSH/TC1/D6/20*/
Functions
void ccn_setup_sockaddr_un (const char *portstr, struct sockaddr_un *result)
Set up a unix-domain socket address for contacting ccnd.
int ccn_setup_sockaddr_in (const char *name, struct sockaddr *result, int length)
Set up a Internet socket address for contacting ccnd.
Detailed Description
Part of the CCNx C Library.
Copyright (C) 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_setup_sockaddr_un.c.
Define Documentation
#define AI_ADDRCONFIG 0 /*IEEE Std 1003.1-2001/Cor 1-2002, item XSH/TC1/D6/20*/
Definition at line 34 of file ccn_setup_sockaddr_un.c.
Referenced by ccn_setup_sockaddr_in(), and open_socket().
Function Documentation
int ccn_setup_sockaddr_in (const char * name, struct sockaddr * result, int length)
Set up a Internet socket address for contacting ccnd.
The name must be of the form "tcp[4|6][:port]" If there is no port specified, the environment variable CCN_LOCAL_PORT is checked. Bad port specifications will result in the default port (9695) being used. If neither "4" nor "6" is present, the code will prefer the IPv4 localhost address.
Returns:
0 on success, -1 on error
Definition at line 85 of file ccn_setup_sockaddr_un.c.
Referenced by ccn_connect().
void ccn_setup_sockaddr_un (const char * portstr, struct sockaddr_un * result)
Set up a unix-domain socket address for contacting ccnd.
If the environment variable CCN_LOCAL_SOCKNAME is set and not empty, it supplies the name stem; otherwise the compiled-in default is used.
If portstr is NULL or empty, the environment variable CCN_LOCAL_PORT is checked. If the portstr specifies something other than the ccnx registered port number, the socket name is modified accordingly.
Parameters:
portstr - numeric port; use NULL for default.
result - the returned unix domain sockaddr
Definition at line 55 of file ccn_setup_sockaddr_un.c.
Referenced by ccn_connect(), ccnd_get_local_sockname(), main(), and r_net_get_local_sockname().