Content-Centric Networking in C: lib/ccn_header.c File Reference
ccn_header.c File Reference
Support for parsing and creating file headers.
Functions
int ccn_parse_tagged_required_uintmax (struct ccn_buf_decoder *d, enum ccn_dtag dtag, uintmax_t *result)
struct ccn_header * ccn_header_parse (const unsigned char *p, size_t size)
Parse a ccnb-encoded Header.
void ccn_header_destroy (struct ccn_header **ph)
int ccnb_append_header (struct ccn_charbuf *c, const struct ccn_header *h)
struct ccn_header * ccn_get_header (struct ccn *h, struct ccn_charbuf *name, int timeout)
Variables
const unsigned char meta [8] = {CCN_MARKER_CONTROL, '.', 'M', 'E', 'T', 'A', '.', 'M'}
Detailed Description
Support for parsing and creating file headers.
Part of the CCNx C Library.
Copyright (C) 2009, 2013 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_header.c.
Function Documentation
struct ccn_header* ccn_get_header (struct ccn * h, struct ccn_charbuf * name, int timeout) [read]
Definition at line 137 of file ccn_header.c.
void ccn_header_destroy (struct ccn_header ** ph)
Definition at line 104 of file ccn_header.c.
Referenced by ccn_header_parse(), and main().
struct ccn_header* ccn_header_parse (const unsigned char * p, size_t size) [read]
Parse a ccnb-encoded Header.
Definition at line 50 of file ccn_header.c.
Referenced by ccn_get_header(), and main().
int ccn_parse_tagged_required_uintmax (struct ccn_buf_decoder * d, enum ccn_dtag dtag, uintmax_t * result)
Definition at line 34 of file ccn_header.c.
Referenced by ccn_header_parse().
int ccnb_append_header (struct ccn_charbuf * c, const struct ccn_header * h)
Definition at line 115 of file ccn_header.c.
Referenced by main().
Variable Documentation
const unsigned char meta[8] = {CCN_MARKER_CONTROL, '.', 'M', 'E', 'T', 'A', '.', 'M'}
Definition at line 31 of file ccn_header.c.
Referenced by ccn_get_header().