Content-Centric Networking in C: lib/ccn_digest.c File Reference
ccn_digest.c File Reference
Support for creating digests.
Functions
struct ccn_digest * ccn_digest_create (enum ccn_digest_id id)
void ccn_digest_destroy (struct ccn_digest **pd)
enum ccn_digest_id ccn_digest_getid (struct ccn_digest *d)
size_t ccn_digest_size (struct ccn_digest *d)
void ccn_digest_init (struct ccn_digest *d)
int ccn_digest_update (struct ccn_digest *d, const void *data, size_t size)
int ccn_digest_final (struct ccn_digest *d, unsigned char *result, size_t digest_size)
Detailed Description
Support for creating digests.
Part of the CCNx C Library.
Copyright (C) 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_digest.c.
Function Documentation
struct ccn_digest* ccn_digest_create (enum ccn_digest_id id) [read]
Definition at line 32 of file ccn_digest.c.
Referenced by ccn_aes_digest(), ccn_digest_Content(), ccn_digest_ContentObject(), ccn_locate_key(), ccns_slice_name(), main(), sendSlice(), and SyncAddRoot().
void ccn_digest_destroy (struct ccn_digest ** pd)
Definition at line 54 of file ccn_digest.c.
Referenced by ccn_aes_keystore_file_init(), ccn_digest_Content(), ccn_digest_ContentObject(), ccn_locate_key(), ccns_slice_name(), sendSlice(), and SyncAddRoot().
int ccn_digest_final (struct ccn_digest * d, unsigned char * result, size_t digest_size)
Definition at line 92 of file ccn_digest.c.
Referenced by ccn_aes_digest(), ccn_digest_Content(), ccn_digest_ContentObject(), ccn_locate_key(), ccns_slice_name(), main(), sendSlice(), and SyncAddRoot().
enum ccn_digest_id ccn_digest_getid (struct ccn_digest * d)
Definition at line 63 of file ccn_digest.c.
void ccn_digest_init (struct ccn_digest * d)
Definition at line 75 of file ccn_digest.c.
Referenced by ccn_aes_digest(), ccn_digest_Content(), ccn_digest_ContentObject(), ccn_locate_key(), ccns_slice_name(), main(), sendSlice(), and SyncAddRoot().
size_t ccn_digest_size (struct ccn_digest * d)
Definition at line 69 of file ccn_digest.c.
Referenced by ccn_locate_key(), ccns_slice_name(), main(), sendSlice(), and SyncAddRoot().
int ccn_digest_update (struct ccn_digest * d, const void * data, size_t size)
Definition at line 82 of file ccn_digest.c.
Referenced by ccn_aes_digest(), ccn_digest_Content(), ccn_digest_ContentObject(), ccn_locate_key(), ccns_slice_name(), main(), sendSlice(), and SyncAddRoot().