Content-Centric Networking in C: ccnd/ccndsmoketest.c File Reference
ccndsmoketest.c File Reference
Simple program for smoke-test of ccnd.
Defines
#define CRLF "\r\n"
#define HTTPVERSION "1.1"
Functions
static void printraw (char *p, int n)
static int open_local (struct sockaddr_un *sa, const char *verb)
static int open_socket (const char *host, const char *portstr, int sock_type)
static void send_ccnb_file (int sock, FILE *msgs, const char *filename, int is_dgram)
static int is_ccnb_name (const char *s)
void write_to_stream (FILE *outstream, const void *rawbuf, size_t rawlen)
int main (int argc, char **argv)
Variables
char rawbuf [1024 *1024]
Detailed Description
Simple program for smoke-test of ccnd.
Copyright (C) 2008-2013 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccndsmoketest.c.
Define Documentation
#define CRLF "\r\n"
Definition at line 44 of file ccndsmoketest.c.
Referenced by main().
#define HTTPVERSION "1.1"
Definition at line 45 of file ccndsmoketest.c.
Referenced by main().
Function Documentation
static int is_ccnb_name (const char * s) [static]
Definition at line 195 of file ccndsmoketest.c.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 214 of file ccndsmoketest.c.
static int open_local (struct sockaddr_un * sa, const char * verb) [static]
Definition at line 67 of file ccndsmoketest.c.
Referenced by main().
static int open_socket (const char * host, const char * portstr, int sock_type) [static]
Definition at line 94 of file ccndsmoketest.c.
Referenced by main().
static void printraw (char * p, int n) [static]
Definition at line 50 of file ccndsmoketest.c.
Referenced by main().
static void send_ccnb_file (int sock, FILE * msgs, const char * filename, int is_dgram) [static]
Definition at line 154 of file ccndsmoketest.c.
Referenced by main().
void write_to_stream (FILE * outstream, const void * rawbuf, size_t rawlen)
Definition at line 202 of file ccndsmoketest.c.
Referenced by main().
Variable Documentation
char rawbuf[1024 *1024]
Definition at line 47 of file ccndsmoketest.c.
Referenced by main(), and send_ccnb_file().