Content-Centric Networking in C: ccnd/ccnd_msg.c File Reference
ccnd_msg.c File Reference
Logging support for ccnd.
Functions
void ccnd_msg (struct ccnd_handle *h, const char *fmt,...)
Produce ccnd debug output.
void ccnd_append_excludes (struct ccn_charbuf *c, const unsigned char *ccnb, struct ccn_parsed_interest *pi, int limit)
Construct a printable representation of an Interest's excludes, and append it to the supplied ccn_charbuf.
void ccnd_debug_ccnb (struct ccnd_handle *h, int lineno, const char *msg, struct face *face, const unsigned char *ccnb, size_t ccnb_size)
Produce a ccnd debug trace entry.
void ccnd_debug_content (struct ccnd_handle *h, int lineno, const char *msg, struct face *face, struct content_entry *content)
Produce a ccnd debug trace entry for content.
Variables
const char * ccnd_usage_message = " A prefix stem to use for generating guest prefixes\n"
CCND Usage message.
Detailed Description
Logging support for ccnd.
Part of ccnd - the CCNx Daemon.
Copyright (C) 2008-2013 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccnd_msg.c.
Function Documentation
void ccnd_append_excludes (struct ccn_charbuf * c, const unsigned char * ccnb, struct ccn_parsed_interest * pi, int limit)
Construct a printable representation of an Interest's excludes, and append it to the supplied ccn_charbuf.
Parameters:
c pointer to the charbuf to append to
ccnb pointer to ccnb-encoded Interest
pi pointer to the parsed interest data
limit number of components to print before ending with " .."
Definition at line 90 of file ccnd_msg.c.
Referenced by ccnd_debug_ccnb().
void ccnd_debug_ccnb (struct ccnd_handle * h, int lineno, const char * msg, struct face * face, const unsigned char * ccnb, size_t ccnb_size)
Produce a ccnd debug trace entry.
Output is produced by calling ccnd_msg.
Parameters:
h the ccnd handle
lineno caller's source line number (usually __LINE__)
msg a short text tag to identify the entry
face handle of associated face; may be NULL
ccnb points to ccnb-encoded Interest or ContentObject
ccnb_size is in bytes
Definition at line 166 of file ccnd_msg.c.
Referenced by age_forwarding(), ccnd_answer_req(), ccnd_reg_prefix(), ccnd_req_unreg(), do_propagate(), drop_nonlocal_interest(), next_child_at_level(), process_incoming_content(), process_incoming_interest(), stuff_and_send(), and stuff_link_check().
void ccnd_debug_content (struct ccnd_handle * h, int lineno, const char * msg, struct face * face, struct content_entry * content)
Produce a ccnd debug trace entry for content.
This takes a content handle so that we can print the already-computed implicit digest.
Definition at line 266 of file ccnd_msg.c.
Referenced by content_tree_trim(), face_send_queue_insert(), process_incoming_content(), process_incoming_interest(), remove_content(), and send_content().
void ccnd_msg (struct ccnd_handle * h, const char * fmt, ...)
Produce ccnd debug output.
For debugging.
Output is produced via h->logger under the control of h->debug; prepends decimal timestamp and process identification. Caller should not supply newlines.
Parameters:
h the ccnd handle
fmt printf-like format string
Definition at line 46 of file ccnd_msg.c.
Referenced by accept_connection(), adjstate_change_db(), ccn_append_link_stuff(), ccnd_close_fd(), ccnd_collect_stats(), ccnd_create(), ccnd_debug_ccnb(), ccnd_debug_content(), ccnd_faceattr_strategy_impl(), ccnd_getboundsocket(), ccnd_init_internal_keystore(), ccnd_listen_on_address(), ccnd_listen_on_wildcards(), ccnd_nack(), ccnd_new_face_msg(), ccnd_parse_uri_list(), ccnd_req_destroyface(), ccnd_req_newface(), ccnd_run(), ccnd_send(), ccnd_setsockopt_v6only(), ccnd_start_notice(), ccnd_stats_http_set_debug(), ccnd_trace_strategy_impl(), check_comm_file(), content_enqueuex(), content_sender(), create_local_listener(), do_deferred_write(), do_propagate(), establish_min_recv_bufsize(), face_send_queue_insert(), finalize_face(), get_outbound_faces(), handle_send_error(), ie_next_usec(), main(), make_connection(), pfi_set_expiry_from_lifetime(), process_incoming_content(), process_incoming_interest(), process_incoming_link_message(), process_input(), process_input_buffer(), process_input_message(), record_connection(), setup_multicast(), shutdown_client_fd(), start_ccnd(), and update_forward_to().
Variable Documentation
const char* ccnd_usage_message = " A prefix stem to use for generating guest prefixes\n"
CCND Usage message.
Definition at line 291 of file ccnd_msg.c.
Referenced by main().