Content-Centric Networking in C: ccnd/android_main.c File Reference
android_main.c File Reference
Functions
static int logger (void *loggerdata, const char *format, va_list ap)
Copyright (C) 2009,2010 Palo Alto Research Center, Inc.
int start_ccnd (void)
Function Documentation
static int logger (void * loggerdata, const char * format, va_list ap) [static]
Copyright (C) 2009,2010 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. This module replaces ccnd_main on the android platform. It includes the methods a JNI interface would use to start ccnd.
Definition at line 26 of file android_main.c.
Referenced by ccn_setup_socket(), ccnd_create(), r_init_create(), and start_ccnd().
int start_ccnd (void)
Definition at line 32 of file android_main.c.