Content-Centric Networking in C: ccnd/ccnd_strategy.h File Reference
ccnd_strategy.h File Reference
This header defines the API to be used by strategy callouts.
Data Structures
struct nameprefix_state
This is a place for strategies to record state that is attached to a given name prefix.
struct pit_face_item
Per-face PIT information.
struct ccn_strategy
State for the strategy engine.
struct strategy_class
struct strategy_instance
Defines
#define CCN_UNINIT (~0U)
initial value of strategy vars
#define CCN_MAGIC_MASK 0x00FFFFFF
for magic number
#define CCN_AGED 0x10000000
for aging
#define CCND_STRATEGY_STATE_N 4
number of per-prefix strategy vars
#define CCN_STATESIZECHECK(XX, T) struct XX {char x[(int)((sizeof(T) > sizeof(struct nameprefix_state)) ? -1 : 1)];}
Use this macro to make sure that overlaying structures are not oversize.
#define CCN_NOFACEID (~0U) /** denotes no face */
A faceid is declared simply as unsigned.
#define TYPICAL_NONCE_SIZE 12
actual allocated size may differ
#define CCND_PFI_NONCESZ 0x00FF
Mask for actual nonce size.
#define CCND_PFI_UPSTREAM 0x0100
Tracks upstream (sent interest)
#define CCND_PFI_UPENDING 0x0200
Has been sent upstream (initially cleared, set for tap face)
#define CCND_PFI_SENDUPST 0x0400
Should be sent upstream (send upstream at expiry)
#define CCND_PFI_UPHUNGRY 0x0800
Upstream hungry, cupboard bare (upstream expired, no unexpired downstream to refresh)
#define CCND_PFI_DNSTREAM 0x1000
Tracks downstream (recvd interest)
#define CCND_PFI_PENDING 0x2000
Pending for immediate data.
#define CCND_PFI_SUPDATA 0x4000
Suppressed data reply.
#define CCND_PFI_ATTENTION 0x10000
Upstream needs attention from strategy.
#define CCND_PFI_INACTIVE 0x20000
Face is nonresponsive, may have lost communication.
#define CCND_PFI_DCFACE 0x100000
This upstream is a Direct Control face (gets data if unanswered for a long time)
#define FAI_VALID 0
Face attribute "valid".
#define FAM_VALID (1U << FAI_VALID)
#define FAI_APPLICATION 1
Face attribute "application".
#define FAM_APPLICATION (1U << FAI_APPLICATION)
#define FAM_APP FAM_APPLICATION
#define FAI_BROADCAST_CAPABLE 2
Face attribute "broadcastcapable".
#define FAM_BROADCAST_CAPABLE (1U << FAI_BROADCAST_CAPABLE)
#define FAM_BCAST FAM_BROADCAST_CAPABLE
#define FAI_DIRECT_CONTROL 3
Face attribute "directcontrol".
#define FAM_DIRECT_CONTROL (1U << FAI_DIRECT_CONTROL)
#define FAM_DC FAM_DIRECT_CONTROL
Typedefs
typedef uint32_t ccn_wrappedtime
Used for keeping track of interest expiry.
typedef void(* strategy_callout_proc)(struct ccnd_handle *h, struct strategy_instance *instance, struct ccn_strategy *s, enum ccn_strategy_op op, unsigned faceid)
Strategies are implemented by a procedure that is called at critical junctures in the lifetime of a pending interest.
Enumerations
enum ccn_strategy_op {
CCNST_NOP, CCNST_INIT, CCNST_FIRST, CCNST_UPDATE,
CCNST_EXPUP, CCNST_EXPDN, CCNST_REFRESH, CCNST_TIMER,
CCNST_SATISFIED, CCNST_TIMEOUT, CCNST_FINALIZE
}
Ops for strategy callout.
Functions
void strategy_init_error (struct ccnd_handle *h, struct strategy_instance *instance, const char *message)
Note a strategy initialization error.
struct pit_face_item * send_interest (struct ccnd_handle *h, struct interest_entry *ie, struct pit_face_item *x, struct pit_face_item *p)
Forward an interest message.
void pfi_set_expiry_from_micros (struct ccnd_handle *h, struct interest_entry *ie, struct pit_face_item *p, unsigned micros)
Set the expiry of the pit face item using a time in microseconds from present.
void strategy_getstate (struct ccnd_handle *h, struct ccn_strategy *s, struct nameprefix_state **sst, int k)
Return a pointer to the strategy state records for the name prefix of the given interest entry and up to k-1 parents.
void strategy_settimer (struct ccnd_handle *h, struct interest_entry *ie, int usec, enum ccn_strategy_op op)
Schedule a strategy wakeup.
struct face * ccnd_face_from_faceid (struct ccnd_handle *, unsigned)
Get the face handle for a given faceid.
unsigned face_faceid (struct face *)
Accessors for things a strategy might want to know about a face.
int face_pending_interests (struct face *)
Accessor for number of pending interests received on a face.
int face_outstanding_interests (struct face *)
Accessor for number of outstanding interests sent on a face.
int faceattr_index_from_name (struct ccnd_handle *h, const char *name)
Face attributes.
int faceattr_bool_index_from_name (struct ccnd_handle *h, const char *name)
int faceattr_index_allocate (struct ccnd_handle *h)
int faceattr_index_free (struct ccnd_handle *h, int faceattr_index)
unsigned faceattr_get (struct ccnd_handle *h, struct face *face, int faceattr_index)
int faceattr_set (struct ccnd_handle *h, struct face *face, int faceattr_index, unsigned value)
unsigned faceattr_get_packed (struct ccnd_handle *h, struct face *face)
const char * faceattr_next_name (struct ccnd_handle *h, const char *name)
Stateless enumerator for face attribute names.
void ccnd_msg (struct ccnd_handle *, const char *,...)
For debugging.
uint32_t ccnd_random (struct ccnd_handle *)
A PRNG returning 31-bit pseudo-random numbers.
struct strategy_class * strategy_class_from_id (const char *id)
look up a strategy class
Variables
struct strategy_class ccnd_strategy_classes []
Detailed Description
This header defines the API to be used by strategy callouts.
Part of ccnd - the CCNx Daemon.
Copyright (C) 2013 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccnd_strategy.h.
Define Documentation
#define CCN_AGED 0x10000000
for aging
Definition at line 41 of file ccnd_strategy.h.
Referenced by ccnd_default_strategy_impl(), and check_nameprefix_entries().
#define CCN_MAGIC_MASK 0x00FFFFFF
for magic number
Definition at line 40 of file ccnd_strategy.h.
Referenced by ccnd_default_strategy_impl().
#define CCN_NOFACEID (~0U) /** denotes no face */
A faceid is declared simply as unsigned.
There is one special value.
Definition at line 77 of file ccnd_strategy.h.
Referenced by adjust_predicted_response(), ccnd_answer_by_guid(), ccnd_create(), ccnd_default_strategy_impl(), ccnd_faceid_from_guid(), ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), collect_faces_html(), collect_faces_xml(), create_strategy_instance(), do_propagate(), faceid_from_fd(), finalize_face(), record_connection(), remove_strategy_instance(), sending_fd(), shutdown_client_fd(), strategy_timer(), and update_forward_to().
#define CCN_STATESIZECHECK (XX, T) struct XX {char x[(int)((sizeof(T) > sizeof(struct nameprefix_state)) ? -1 : 1)];}
Use this macro to make sure that overlaying structures are not oversize.
XX is an otherwise unused identifier, and T is the overlaid struct type. This is intended to cause a compilation error if T becomes too large.
Definition at line 66 of file ccnd_strategy.h.
#define CCN_UNINIT (~0U)
initial value of strategy vars
Definition at line 39 of file ccnd_strategy.h.
Referenced by ccnd_default_strategy_impl(), and nameprefix_seek().
#define CCND_PFI_ATTENTION 0x10000
Upstream needs attention from strategy.
Definition at line 105 of file ccnd_strategy.h.
Referenced by ccnd_default_strategy_impl(), ccnd_loadsharing_strategy_impl(), ccnd_null_strategy_impl(), ccnd_parallel_strategy_impl(), do_propagate(), and format_pfi().
#define CCND_PFI_DCFACE 0x100000
This upstream is a Direct Control face (gets data if unanswered for a long time)
Definition at line 107 of file ccnd_strategy.h.
Referenced by do_propagate(), and format_pfi().
#define CCND_PFI_DNSTREAM 0x1000
Tracks downstream (recvd interest)
Definition at line 102 of file ccnd_strategy.h.
Referenced by ccnd_default_strategy_impl(), do_propagate(), format_pfi(), propagate_interest(), send_tap_interests(), and update_npe_children().
#define CCND_PFI_INACTIVE 0x20000
Face is nonresponsive, may have lost communication.
Definition at line 106 of file ccnd_strategy.h.
Referenced by ccnd_loadsharing_strategy_impl(), ccnd_parallel_strategy_impl(), do_propagate(), and format_pfi().
#define CCND_PFI_NONCESZ 0x00FF
Mask for actual nonce size.
Definition at line 97 of file ccnd_strategy.h.
Referenced by pfi_copy_nonce(), pfi_create(), pfi_nonce_matches(), pfi_set_nonce(), pfi_unique_nonce(), and send_interest().
#define CCND_PFI_PENDING 0x2000
Pending for immediate data.
Definition at line 103 of file ccnd_strategy.h.
Referenced by ccnd_collect_stats(), ccnd_default_strategy_impl(), consume_matching_interests(), do_propagate(), finalize_interest(), format_pfi(), is_pending_on(), pfi_destroy(), propagate_interest(), and send_tap_interests().
#define CCND_PFI_SENDUPST 0x0400
Should be sent upstream (send upstream at expiry)
Definition at line 100 of file ccnd_strategy.h.
Referenced by ccnd_default_strategy_impl(), ccnd_loadsharing_strategy_impl(), ccnd_null_strategy_impl(), ccnd_parallel_strategy_impl(), do_propagate(), format_pfi(), and send_interest().
#define CCND_PFI_SUPDATA 0x4000
Suppressed data reply.
Definition at line 104 of file ccnd_strategy.h.
Referenced by format_pfi(), and propagate_interest().
#define CCND_PFI_UPENDING 0x0200
Has been sent upstream (initially cleared, set for tap face)
Definition at line 99 of file ccnd_strategy.h.
Referenced by ccnd_default_strategy_impl(), ccnd_loadsharing_strategy_impl(), do_propagate(), finalize_interest(), format_pfi(), pfi_destroy(), propagate_interest(), send_interest(), and update_npe_children().
#define CCND_PFI_UPHUNGRY 0x0800
Upstream hungry, cupboard bare (upstream expired, no unexpired downstream to refresh)
Definition at line 101 of file ccnd_strategy.h.
Referenced by do_propagate(), format_pfi(), propagate_interest(), and send_interest().
#define CCND_PFI_UPSTREAM 0x0100
Tracks upstream (sent interest)
Definition at line 98 of file ccnd_strategy.h.
Referenced by ccnd_default_strategy_impl(), ccnd_loadsharing_strategy_impl(), do_propagate(), format_pfi(), propagate_interest(), send_tap_interests(), and update_npe_children().
#define CCND_STRATEGY_STATE_N 4
number of per-prefix strategy vars
Definition at line 42 of file ccnd_strategy.h.
Referenced by nameprefix_seek().
#define FAI_APPLICATION 1
Face attribute "application".
If true, the face is deemed to be a local application, by virtue of connection information (e.g., loopback interface or unix-domain socket).
Definition at line 383 of file ccnd_strategy.h.
Referenced by ccnd_create().
#define FAI_BROADCAST_CAPABLE 2
Face attribute "broadcastcapable".
If true, the face can reach multiple peers via broadcast.
Definition at line 392 of file ccnd_strategy.h.
Referenced by ccnd_create().
#define FAI_DIRECT_CONTROL 3
Face attribute "directcontrol".
If true, the face should not be sent interests unless there is no response from any other faces. This may be used by an application that can update the FIB on demand.
Definition at line 403 of file ccnd_strategy.h.
Referenced by ccnd_create().
#define FAI_VALID 0
Face attribute "valid".
If true, the face may be used for interest/data exchange.
Definition at line 374 of file ccnd_strategy.h.
Referenced by ccnd_create().
#define FAM_APP FAM_APPLICATION
Definition at line 385 of file ccnd_strategy.h.
Referenced by adjust_builtin_faceattr().
#define FAM_APPLICATION (1U << FAI_APPLICATION)
Definition at line 384 of file ccnd_strategy.h.
#define FAM_BCAST FAM_BROADCAST_CAPABLE
Definition at line 394 of file ccnd_strategy.h.
Referenced by adjust_builtin_faceattr().
#define FAM_BROADCAST_CAPABLE (1U << FAI_BROADCAST_CAPABLE)
Definition at line 393 of file ccnd_strategy.h.
#define FAM_DC FAM_DIRECT_CONTROL
Definition at line 405 of file ccnd_strategy.h.
Referenced by adjust_builtin_faceattr().
#define FAM_DIRECT_CONTROL (1U << FAI_DIRECT_CONTROL)
Definition at line 404 of file ccnd_strategy.h.
#define FAM_VALID (1U << FAI_VALID)
Definition at line 375 of file ccnd_strategy.h.
Referenced by adjust_builtin_faceattr().
#define TYPICAL_NONCE_SIZE 12
actual allocated size may differ
Definition at line 79 of file ccnd_strategy.h.
Referenced by ccnd_debug_nonce(), pfi_create(), pfi_set_nonce(), and propagate_interest().
Typedef Documentation
typedef uint32_t ccn_wrappedtime
Used for keeping track of interest expiry.
Modulo 2**32 - time units and origin are arbitrary and private.
Definition at line 74 of file ccnd_strategy.h.
typedef void(* strategy_callout_proc)(struct ccnd_handle *h, struct strategy_instance *instance, struct ccn_strategy *s, enum ccn_strategy_op op, unsigned faceid)
Strategies are implemented by a procedure that is called at critical junctures in the lifetime of a pending interest.
If op is CCNST_FIRST, faceid tells the interest arrival face (downstream). If op is CCNST_SATISFIED, faceid tells the content arrival face (upstream).
Definition at line 237 of file ccnd_strategy.h.
Enumeration Type Documentation
enum ccn_strategy_op
Ops for strategy callout.
These are passed to the strategy callout to inform it of the current situation.
CCNST_NOP is useful as an argument to pass to strategy_settimer() when the callout wishes to cancel a pending strategy timer. CCNST_NOP is not expected to actually be passed to a callout, but if it is, the strategy should take no action that changes forwarding behavior.
CCNST_INIT provides an opportunity for the callout to allocate and initialize any private instance state that it may require. This happens when a new strategy is attached to a given prefix. If the strategy uses parameters, this call is the appropriate time to parse them and save the resulting values in the private instance state for rapid access in the more time-critical calls. The callout should use strategy_init_error() to report problems with the parameter string.
CCNST_FIRST indicates the creation of a new PIT entry due to an arriving interest. Since there was no existing state for similar interests, there will be exactly one downstream in the pfi list. The upstreams in the list are those that the FIB has indicated are eligible to receive the interests. The expiry times are initially set to the current time, so if the strategy callout sets CCND_PFI_SENDUPST on, an upstream, the interest will be sent to the marked upstreams as soon as the callout returns. At the time of the CCNST_FIRST call, some upstreams may have already been fed (such as those with the TAP forwarding flag). These will have CCND_PFI_UPENDING set. The strategy callout should generally ignore such entries. The faceid indicates the initial downstream face.
CCNST_UPDATE indicates at least one upstream has become eligible receive a new copy of the interest, because any previously sent interest has expired and an unexpired downsream is available; or a new upstream has been added, because of a new prefix registration, or because a second downstream has made the initial upstream eligible. The affected upstreams will have CCND_PFI_ATTENTION set and an expiry in the near future. For these entries, the strategy must clear CCND_PFI_ATTENTION and may choose to set CCND_PFI_SENDUPST on the subset of the affected upstreams that it selects. The value of faceid is not interesting.
CCNST_EXPUP indicates an upstream is expiring. This happens when and only when an interest has been sent to the upstream face and the associated lifetime has elapsed without the receipt of matching content. The faceid indicates the expiring upstream face.
CCNST_EXPDN indicates the downstream is expiring. The faceid indicates the expiring downstream face.
CCNST_REFRESH indicates a new, similar, interest message has arrived. a previously existing downstream face. Its expiry Its expiry will have been updated accordingly. The strategy likely does not need to do anything special with this case, because it will get separate calls for each of the upstreams when their respective expiries occur. The faceid indicates the refreshed downstream face.
CCNST_TIMER is intended as an argument for strategy_settimer() so that the strategy callout can get control at a time that does not need to correspond with the expiry of an upstream or downstream. The value of faceid is not interesting.
CCNST_SATISFIED indicates the arrival of a matching content object. After the strategy callout returns, all of the downstreams that have CCND_PFI_PENDING set will be sent copies of the data, and the PIT entry will be removed. The faceid indicates the source of the matching content.
CCNST_TIMEOUT indicates that all downstreams and upstreams have expired. The PIT entry will go away as soon as the callout returns. The value of faceid is not interesting.
CCNST_FINALIZE indicates the strategy instance is about to go away. The strategy callout should deallocate any strategy-private memory. The value of faceid is not interesting.
Enumerator:
CCNST_NOP
CCNST_INIT
CCNST_FIRST
CCNST_UPDATE
CCNST_EXPUP
CCNST_EXPDN
CCNST_REFRESH
CCNST_TIMER
CCNST_SATISFIED
CCNST_TIMEOUT
CCNST_FINALIZE
Definition at line 214 of file ccnd_strategy.h.
Function Documentation
struct face* ccnd_face_from_faceid (struct ccnd_handle * h, unsigned faceid) [read]
Get the face handle for a given faceid.
Strategy routines should use the accessors provided.
Returns:
NULL if face does not exist.
Definition at line 309 of file ccnd.c.
Referenced by adjacency_do_refresh(), adjacency_do_reset(), adjacency_timed_reset(), adjust_builtin_faceattr(), ccnd_answer_by_guid(), ccnd_answer_req(), ccnd_collect_stats(), ccnd_do_solicit(), ccnd_faceattr_strategy_impl(), ccnd_flush_guid_cob(), ccnd_loadsharing_strategy_impl(), ccnd_req_guest(), format_pfi(), incoming_adjacency(), post_face_notice(), schedule_adjacency_negotiation(), and solicit_response().
void ccnd_msg (struct ccnd_handle * h, const char * fmt, ...)
For debugging.
For debugging.
Output is produced via h->logger under the control of h->debug; prepends decimal timestamp and process identification. Caller should not supply newlines.
Parameters:
h the ccnd handle
fmt printf-like format string
Definition at line 46 of file ccnd_msg.c.
Referenced by accept_connection(), adjstate_change_db(), ccn_append_link_stuff(), ccnd_close_fd(), ccnd_collect_stats(), ccnd_create(), ccnd_debug_ccnb(), ccnd_debug_content(), ccnd_faceattr_strategy_impl(), ccnd_getboundsocket(), ccnd_init_internal_keystore(), ccnd_listen_on_address(), ccnd_listen_on_wildcards(), ccnd_nack(), ccnd_new_face_msg(), ccnd_parse_uri_list(), ccnd_req_destroyface(), ccnd_req_newface(), ccnd_run(), ccnd_send(), ccnd_setsockopt_v6only(), ccnd_start_notice(), ccnd_stats_http_set_debug(), ccnd_trace_strategy_impl(), check_comm_file(), content_enqueuex(), content_sender(), create_local_listener(), do_deferred_write(), do_propagate(), establish_min_recv_bufsize(), face_send_queue_insert(), finalize_face(), get_outbound_faces(), handle_send_error(), ie_next_usec(), main(), make_connection(), pfi_set_expiry_from_lifetime(), process_incoming_content(), process_incoming_interest(), process_incoming_link_message(), process_input(), process_input_buffer(), process_input_message(), record_connection(), setup_multicast(), shutdown_client_fd(), start_ccnd(), and update_forward_to().
uint32_t ccnd_random (struct ccnd_handle *)
A PRNG returning 31-bit pseudo-random numbers.
Definition at line 496 of file ccnd.c.
Referenced by ccnd_default_strategy_impl(), ccnd_loadsharing_strategy_impl(), and ccnd_parallel_strategy_impl().
unsigned face_faceid (struct face * face)
Accessors for things a strategy might want to know about a face.
Definition at line 316 of file ccnd.c.
int face_outstanding_interests (struct face *)
Accessor for number of outstanding interests sent on a face.
Definition at line 334 of file ccnd.c.
Referenced by ccnd_loadsharing_strategy_impl().
int face_pending_interests (struct face *)
Accessor for number of pending interests received on a face.
Definition at line 325 of file ccnd.c.
int faceattr_bool_index_from_name (struct ccnd_handle * h, const char * name)
Definition at line 760 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl(), ccnd_loadsharing_strategy_impl(), and faceattr_declare().
unsigned faceattr_get (struct ccnd_handle * h, struct face * face, int faceattr_index)
Definition at line 831 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl(), and ccnd_loadsharing_strategy_impl().
unsigned faceattr_get_packed (struct ccnd_handle * h, struct face * face)
Definition at line 843 of file ccnd.c.
int faceattr_index_allocate (struct ccnd_handle * h)
Definition at line 766 of file ccnd.c.
int faceattr_index_free (struct ccnd_handle * h, int faceattr_index)
Definition at line 781 of file ccnd.c.
int faceattr_index_from_name (struct ccnd_handle * h, const char * name)
Face attributes.
To help strategies do their work, there is provision for faces to carry a collection of attributes. These have associated values, which can be either boolean or numeric (non-negative integers). Strategies may set and get these values using an attribute index to say which attribute is desired. Some attributes are set by ccnd, based upon things it knows about the face. Others have associated names, and may be set from the outside (using the face managment protocol). Still others are private to strategy implementations, and need not have a name, only a dynamically assigned index.
The first 32 indices (0 through 31) are reserved for single-bit attributes. These may be read all at once using faceattr_get_packed, but are set using the general faceattr_set call. They may also be read using faceattr_get. In the packed form, the attribute with index 0 is stored in the low-order bit, so the bits may be tested using straightforward shifts and masks. After the first 32 single-bit attributes have been created, any additional requests will be fullfulled with attributes capable of carrying numeric values.
Newly created attributes are initialized to 0/false.
Some attributes are created and set by ccnd, reflecting things about faces that may be relevant to the operation of strategies. These are assigned with predeclared indices, so it is not necessary to learn the index from the name at runtime (although this is allowed). All of the built-in single-bit attributes have small indices, and so are accessible using faceattr_get_packed. Macros for corresponding bit masks are also provided.
Definition at line 754 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl(), faceattr_declare(), and faceattr_index_allocate().
const char* faceattr_next_name (struct ccnd_handle * h, const char * name)
Stateless enumerator for face attribute names.
Call with NULL to get the first name. Returns NULL after the last name. The order is unspecified. Generated names are provided for private attrs.
Definition at line 864 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl().
int faceattr_set (struct ccnd_handle * h, struct face * face, int faceattr_index, unsigned value)
Definition at line 798 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl(), and ccnd_loadsharing_strategy_impl().
void pfi_set_expiry_from_micros (struct ccnd_handle * h, struct interest_entry * ie, struct pit_face_item * p, unsigned micros)
Set the expiry of the pit face item using a time in microseconds from present.
Does not set the renewed timestamp.
Definition at line 4053 of file ccnd.c.
Referenced by ccnd_default_strategy_impl().
struct pit_face_item* send_interest (struct ccnd_handle * h, struct interest_entry * ie, struct pit_face_item * x, struct pit_face_item * p) [read]
Forward an interest message.
The strategy routine may choose to call this directly, and/or update the pfi entries so that the interest will be forwarded on a schedule. If send_interest is called, p is updated to reflect the new state.
x is downstream (the interest came from x). p is upstream (the interest is to be forwarded to p).
Returns:
p (or its reallocated replacement).
x is downstream (the interest came from x). p is upstream (the interest is to be forwarded to p).
Returns:
p (or its reallocated replacement).
Definition at line 3612 of file ccnd.c.
Referenced by ccnd_default_strategy_impl(), do_propagate(), and send_tap_interests().
struct strategy_class* strategy_class_from_id (const char * id) [read]
look up a strategy class
Definition at line 4629 of file ccnd.c.
Referenced by ccnd_req_strategy(), ccnd_trace_strategy_impl(), and get_strategy_instance().
void strategy_getstate (struct ccnd_handle * h, struct ccn_strategy * s, struct nameprefix_state ** sst, int k)
Return a pointer to the strategy state records for the name prefix of the given interest entry and up to k-1 parents.
The sst array is filled in; NULL values are provided as needed. The item sst[0] corresponds with the name inside the interest, and is never NULL unless s is NULL. The remaining entries are for successively shorter prefixes.
Definition at line 3707 of file ccnd.c.
Referenced by ccnd_default_strategy_impl().
void strategy_init_error (struct ccnd_handle * h, struct strategy_instance * instance, const char * message)
Note a strategy initialization error.
A call to this during the CCNST_INIT callout will do appropriate logging and error reporting, and cause the instance to be removed after the termination of the intialization callout.
Do not call from other contexts.
Definition at line 3413 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl(), and ccnd_trace_strategy_impl().
void strategy_settimer (struct ccnd_handle * h, struct interest_entry * ie, int usec, enum ccn_strategy_op op)
Schedule a strategy wakeup.
This causes the associated strategy callout to be called at a later time. The op will be passed to the deferred invocation.
Any previously scheduled wakeup will be cancelled. To just cancel any existing wakeup, pass CCNST_NOP.
Any previously wakeup will be cancelled.
Definition at line 3690 of file ccnd.c.
Referenced by ccnd_default_strategy_impl().
Variable Documentation
struct strategy_class ccnd_strategy_classes[]
Referenced by strategy_class_from_id().