Content-Centric Networking in C: libexec/ccndc-srv.c File Reference
ccndc-srv.c File Reference
ccndc handling of SRV lookups
Defines
#define BIND_8_COMPAT
#define NS_MAXMSG 65535
#define T_SRV 33
#define OP_REG 0
#define OP_UNREG 1
Functions
enum ccn_upcall_res incoming_interest (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
Interest handler.
void ccndc_daemonize (struct ccndc_data *ccndc)
Register / prefix and start dynamically creating entries based on SRV records.
int ccndc_query_srv (const unsigned char *domain, int domain_size, char **hostp, int *portp, char **proto)
Query SRV record of the domain.
Detailed Description
ccndc handling of SRV lookups
A CCNx program.
Copyright (C) 2009-2013 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccndc-srv.c.
Define Documentation
#define BIND_8_COMPAT
Definition at line 30 of file ccndc-srv.c.
#define NS_MAXMSG 65535
Definition at line 42 of file ccndc-srv.c.
Referenced by ccndc_query_srv().
#define OP_REG 0
Definition at line 55 of file ccndc-srv.c.
#define OP_UNREG 1
Definition at line 56 of file ccndc-srv.c.
#define T_SRV 33
Definition at line 52 of file ccndc-srv.c.
Referenced by ccndc_query_srv().
Function Documentation
void ccndc_daemonize (struct ccndc_data * ccndc)
Register / prefix and start dynamically creating entries based on SRV records.
This call will block thread forever
Definition at line 72 of file ccndc-srv.c.
Referenced by main().
int ccndc_query_srv (const unsigned char * domain, int domain_size, char ** hostp, int * portp, char ** proto)
Query SRV record of the domain.
Parameters:
domain domain name
domain_size size of the "domain" variable
hostp [out] gateway's IP address specified by an SRV record
portp [out] gateway's port specified by an SRV record
proto [out] gateway's protocol specified by an SRV record
Returns:
0 on success
Definition at line 90 of file ccndc-srv.c.
Referenced by ccndc_srv().
static enum ccn_upcall_res incoming_interest (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info)
Interest handler.
Definition at line 203 of file ccndc-srv.c.
Referenced by ccndc_daemonize(), chat_main(), and main().