Content-Centric Networking in C: ccnd/ccnd.c File Reference
ccnd.c File Reference
Defines
#define CCND_WTHZ 1000U
Frequency of wrapped timer.
#define WTHZ ((unsigned)(CCND_WTHZ))
#define CCND_CACHE_MARGIN 10
Allow a few extra entries in the cache to allow for output queuing.
#define CCND_MAX_MATCH_PROBES 50000
Maximum number of probes when searching the cache for a match.
Typedefs
typedef void(* loggerproc)(void *, const char *,...)
Functions
static void cleanup_at_exit (void)
Main program of ccnd - the CCNx Daemon.
static void unlink_at_exit (const char *path)
Record the name of the unix-domain listener.
static int create_local_listener (struct ccnd_handle *h, const char *sockname, int backlog)
Create a listener on a unix-domain socket.
static struct face * record_connection (struct ccnd_handle *h, int fd, struct sockaddr *who, socklen_t wholen, int setflags)
Make a new face entered in the faces_by_fd table.
static void process_input_message (struct ccnd_handle *h, struct face *face, unsigned char *msg, size_t size, int pdu_ok)
Process an incoming message.
static void process_input (struct ccnd_handle *h, int fd)
Process the input from a socket.
static int ccn_stuff_interest (struct ccnd_handle *h, struct face *face, struct ccn_charbuf *c)
Stuff a PDU with interest messages that will fit.
static void do_deferred_write (struct ccnd_handle *h, int fd)
Do deferred sends.
static struct face * get_dgram_source (struct ccnd_handle *h, struct face *face, struct sockaddr *addr, socklen_t addrlen, int why)
Get (or create) the face associated with a given sockaddr.
static struct content_entry * content_from_accession (struct ccnd_handle *h, ccn_cookie accession)
Convert an accession to its associated content handle.
static int is_stale (struct ccnd_handle *h, struct content_entry *content)
Check to see whether content is stale.
static void mark_stale (struct ccnd_handle *h, struct content_entry *content)
Mark content as stale.
static struct content_entry * content_next (struct ccnd_handle *h, struct content_entry *content)
Advance to the next entry in the nametree.
static void reap_needed (struct ccnd_handle *h, int init_delay_usec)
static void check_comm_file (struct ccnd_handle *h)
static int nameprefix_seek (struct ccnd_handle *h, struct hashtb_enumerator *e, const unsigned char *msg, struct ccn_indexbuf *comps, int ncomps)
Creates a nameprefix entry if it does not already exist, together with all of its parents.
static void register_new_face (struct ccnd_handle *h, struct face *face)
Called when a face is first created, and (perhaps) a second time in the case that a face transitions from the undecided state.
static void update_forward_to (struct ccnd_handle *h, struct nameprefix_entry *npe)
Set up forward_to list for a name prefix entry.
static void stuff_and_send (struct ccnd_handle *h, struct face *face, const unsigned char *data1, size_t size1, const unsigned char *data2, size_t size2, const char *tag, int lineno)
Send a message in a PDU, possibly stuffing other interest messages into it.
static void ccn_link_state_init (struct ccnd_handle *h, struct face *face)
Set up to send one sequence number to see it the other side wants to play.
static void ccn_append_link_stuff (struct ccnd_handle *h, struct face *face, struct ccn_charbuf *c)
Append a sequence number if appropriate.
static int process_incoming_link_message (struct ccnd_handle *h, struct face *face, enum ccn_dtag dtag, unsigned char *msg, size_t size)
Process an incoming link message.
static void process_internal_client_buffer (struct ccnd_handle *h)
Process messages from our internal client.
static int nonce_ok (struct ccnd_handle *h, struct face *face, const unsigned char *interest_msg, struct ccn_parsed_interest *pi, const unsigned char *nonce, size_t noncesize)
Look for duplication of interest nonces.
static void pfi_destroy (struct ccnd_handle *h, struct interest_entry *ie, struct pit_face_item *p)
Remove the pit face item from the interest entry.
static struct pit_face_item * pfi_set_nonce (struct ccnd_handle *h, struct interest_entry *ie, struct pit_face_item *p, const unsigned char *nonce, size_t noncesize)
Set the nonce in a pit face item.
static int pfi_nonce_matches (struct pit_face_item *p, const unsigned char *nonce, size_t size)
Return true iff the nonce in p matches the given one.
static struct pit_face_item * pfi_copy_nonce (struct ccnd_handle *h, struct interest_entry *ie, struct pit_face_item *p, const struct pit_face_item *src)
Copy a nonce from src into p.
static int pfi_unique_nonce (struct ccnd_handle *h, struct interest_entry *ie, struct pit_face_item *p)
True iff the nonce in p does not occur in any of the other items of the entry.
static int wt_compare (ccn_wrappedtime a, ccn_wrappedtime b)
Compare two wrapped time values.
static void update_npe_children (struct ccnd_handle *h, struct nameprefix_entry *npe, unsigned faceid)
We have a FIB change - accelerate forwarding of existing interests.
static void pfi_set_expiry_from_lifetime (struct ccnd_handle *h, struct interest_entry *ie, struct pit_face_item *p, intmax_t lifetime)
Set the expiry of the pit face item based upon an interest lifetime.
static struct pit_face_item * pfi_seek (struct ccnd_handle *h, struct interest_entry *ie, unsigned faceid, unsigned pfi_flag)
Find the pit face item with the given flag set, or create it if not present.
static void strategy_callout (struct ccnd_handle *h, struct interest_entry *ie, enum ccn_strategy_op op, unsigned faceid)
Call the strategy routine.
static void handle_fatal_signal (int sig)
static int comm_file_ok (void)
Check to see if the unix-domain listener has been unlinked.
static struct ccn_charbuf * charbuf_obtain (struct ccnd_handle *h)
Obtain a charbuf for short-term use.
static void charbuf_release (struct ccnd_handle *h, struct ccn_charbuf *c)
Release a charbuf for reuse.
static struct ccn_indexbuf * indexbuf_obtain (struct ccnd_handle *h)
Obtain an indexbuf for short-term use.
static void indexbuf_release (struct ccnd_handle *h, struct ccn_indexbuf *c)
Release an indexbuf for reuse.
static struct face * face_from_faceid (struct ccnd_handle *h, unsigned faceid)
Looks up a face based on its faceid (private).
struct face * ccnd_face_from_faceid (struct ccnd_handle *h, unsigned faceid)
Looks up a face based on its faceid.
unsigned face_faceid (struct face *face)
Accessor for faceid.
int face_pending_interests (struct face *face)
Accessor for number of pending interests received on a face.
int face_outstanding_interests (struct face *face)
Accessor for number of outstanding interests sent on a face.
static int enroll_face (struct ccnd_handle *h, struct face *face)
Assigns the faceid for a nacent face, calls register_new_face() if successful.
static int choose_face_delay (struct ccnd_handle *h, struct face *face, enum cq_delay_class c)
Decide how much to delay the content sent out on a face.
static struct content_queue * content_queue_create (struct ccnd_handle *h, struct face *face, enum cq_delay_class c)
Create a queue for sending content.
static void content_queue_destroy (struct ccnd_handle *h, struct content_queue **pq)
Destroy a queue.
static void close_fd (int *pfd)
Close an open file descriptor quietly.
static void ccnd_close_fd (struct ccnd_handle *h, unsigned faceid, int *pfd)
Close an open file descriptor, and grumble about it.
uint32_t ccnd_random (struct ccnd_handle *h)
A PRNG returning 31-bit pseudo-random numbers.
int ccnd_set_face_guid (struct ccnd_handle *h, struct face *face, const unsigned char *guid, size_t size)
Associate a guid with a face.
unsigned ccnd_faceid_from_guid (struct ccnd_handle *h, const unsigned char *guid, size_t size)
Return the faceid associated with the guid.
int ccnd_append_face_guid (struct ccnd_handle *h, struct ccn_charbuf *cb, struct face *face)
Append the guid associated with a face to a charbuf.
void ccnd_forget_face_guid (struct ccnd_handle *h, struct face *face)
Forget the guid associated with a face.
void ccnd_generate_face_guid (struct ccnd_handle *h, struct face *face, int size, const unsigned char *lo, const unsigned char *hi)
Generate a new guid for a face.
static void finalize_face (struct hashtb_enumerator *e)
Clean up when a face is being destroyed.
static int faceattr_index_lookup (struct ccnd_handle *h, const char *name, int singlebit)
int faceattr_index_from_name (struct ccnd_handle *h, const char *name)
Face attributes.
int faceattr_bool_index_from_name (struct ccnd_handle *h, const char *name)
int faceattr_index_allocate (struct ccnd_handle *h)
int faceattr_index_free (struct ccnd_handle *h, int faceattr_index)
int faceattr_set (struct ccnd_handle *h, struct face *face, int faceattr_index, unsigned value)
unsigned faceattr_get (struct ccnd_handle *h, struct face *face, int faceattr_index)
unsigned faceattr_get_packed (struct ccnd_handle *h, struct face *face)
static void faceattr_declare (struct ccnd_handle *h, const char *name, int ndx)
const char * faceattr_next_name (struct ccnd_handle *h, const char *name)
Stateless enumerator for face attribute names.
static struct content_entry * find_first_match_candidate (struct ccnd_handle *h, const unsigned char *interest_msg, const struct ccn_parsed_interest *pi)
Find the first candidate that might match the given interest.
static int content_matches_prefix (struct ccnd_handle *h, struct content_entry *content, struct ccn_charbuf *flat)
Check for a prefix match.
static int ex_index_cmp (const unsigned char *a, size_t alen, const unsigned char *b, size_t blen)
static void update_ex_index (struct ccnd_handle *h, int staletime, ccn_cookie c)
Update the index to the expiry queue.
static void content_enqueuex (struct ccnd_handle *h, struct content_entry *content)
Enter content into the content expiry queue according to its staletime.
static void content_dequeuex (struct ccnd_handle *h, struct content_entry *content)
Remove content from the content expiry queue.
int ccnd_n_stale (struct ccnd_handle *h)
Return the number of stale content objects still cached.
static void content_preremove (struct ccn_nametree *ntree, struct ccny *y)
Dequeue content from expiry queue when removing it from nametree.
static void content_finalize (struct ccn_nametree *ntree, struct ccny *y)
Finalize content, freeing the raw ccnb before the content_entry is freed.
static void consume_interest (struct ccnd_handle *h, struct interest_entry *ie)
Consume an interest.
static void finalize_nameprefix (struct hashtb_enumerator *e)
Clean up a name prefix entry when it is removed from the hash table.
static void link_interest_entry_to_nameprefix (struct ccnd_handle *h, struct interest_entry *ie, struct nameprefix_entry *npe)
Link an interest to its name prefix entry.
static void finalize_interest (struct hashtb_enumerator *e)
Clean up an interest_entry when it is removed from its hash table.
static void finalize_nonce (struct hashtb_enumerator *e)
Clean up a nonce_entry when it is removed from its hash table.
static void finalize_guest (struct hashtb_enumerator *e)
Clean up a guest_entry when it is removed from its hash table.
static int establish_min_recv_bufsize (struct ccnd_handle *h, int fd, int minsize)
Adjust socket buffer limit.
static void init_face_flags (struct ccnd_handle *h, struct face *face, int setflags)
Initialize the face flags based upon the addr information and the provided explicit setflags.
static int accept_connection (struct ccnd_handle *h, int listener_fd, int listener_flags)
Accept an incoming SOCK_STREAM connection, creating a new face.
static struct face * make_connection (struct ccnd_handle *h, struct sockaddr *who, socklen_t wholen, int setflags)
Make an outbound stream connection.
static int ccnd_getboundsocket (void *dat, struct sockaddr *who, socklen_t wholen)
Get a bound datagram socket.
static unsigned faceid_from_fd (struct ccnd_handle *h, int fd)
Get the faceid associated with a file descriptor.
static struct face * setup_multicast (struct ccnd_handle *h, struct ccn_face_instance *face_instance, struct sockaddr *who, socklen_t wholen)
Set up a multicast face.
static void shutdown_client_fd (struct ccnd_handle *h, int fd)
Close a socket, destroying the associated face.
static void send_content (struct ccnd_handle *h, struct face *face, struct content_entry *content)
Send a ContentObject.
static enum cq_delay_class choose_content_delay_class (struct ccnd_handle *h, unsigned faceid, int content_flags)
Select the output queue class for a piece of content.
static unsigned randomize_content_delay (struct ccnd_handle *h, struct content_queue *q)
Pick a randomized delay for sending.
static int content_sender (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Scheduled event for sending from a queue.
static int face_send_queue_insert (struct ccnd_handle *h, struct face *face, struct content_entry *content)
Queue a ContentObject to be sent on a face.
static int is_pending_on (struct ccnd_handle *h, struct interest_entry *ie, unsigned faceid)
Return true iff the interest is pending on the given face.
static int consume_matching_interests (struct ccnd_handle *h, struct nameprefix_entry *npe, struct content_entry *content, struct ccn_parsed_ContentObject *pc, struct face *face, struct face *content_face)
Consume matching interests given a nameprefix_entry and a piece of content.
static int match_interests (struct ccnd_handle *h, struct content_entry *content, struct ccn_parsed_ContentObject *pc, struct face *face, struct face *from_face)
Find and consume interests that match given content.
static int stuff_link_check (struct ccnd_handle *h, struct face *face, struct ccn_charbuf *c)
Append a link-check interest if appropriate.
static int check_dgram_faces (struct ccnd_handle *h)
Checks for inactivity on datagram faces.
int ccnd_destroy_face (struct ccnd_handle *h, unsigned faceid)
Destroys the face identified by faceid.
static void check_forward_to (struct ccnd_handle *h, struct ccn_indexbuf **ip)
Remove expired faces from *ip.
static int check_nameprefix_entries (struct ccnd_handle *h)
Ages src info and retires unused nameprefix entries.
static int reap (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Scheduled reap event for retiring expired structures.
static int remove_content (struct ccnd_handle *h, struct content_entry *content)
Remove a content object from the store.
static int age_forwarding (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Age out the old forwarding table entries.
static void age_forwarding_needed (struct ccnd_handle *h)
Make sure a call to age_forwarding is scheduled.
static struct ccn_forwarding * seek_forwarding (struct ccnd_handle *h, struct nameprefix_entry *npe, unsigned faceid)
Look up a forwarding entry, creating it if it is not there.
static int ccnd_reg_prefix (struct ccnd_handle *h, const unsigned char *msg, struct ccn_indexbuf *comps, int ncomps, unsigned faceid, int flags, int expires)
Register or update a prefix in the forwarding table (FIB).
int ccnd_reg_uri (struct ccnd_handle *h, const char *uri, unsigned faceid, int flags, int expires)
Register a prefix, expressed in the form of a URI.
void ccnd_reg_uri_list (struct ccnd_handle *h, struct ccn_charbuf *uris, unsigned faceid, int flags, int expires)
Register prefixes, expressed in the form of a list of URIs.
static int ccnd_nack (struct ccnd_handle *h, struct ccn_charbuf *reply_body, int errcode, const char *errtext)
Replaces contents of reply_body with a ccnb-encoded StatusResponse.
static int check_ccndid (struct ccnd_handle *h, const void *p, size_t sz, struct ccn_charbuf *reply_body)
Check that indicated ccndid matches ours.
static int check_face_instance_ccndid (struct ccnd_handle *h, struct ccn_face_instance *f, struct ccn_charbuf *reply_body)
Check ccndid, given a face instance.
static int check_forwarding_entry_ccndid (struct ccnd_handle *h, struct ccn_forwarding_entry *f, struct ccn_charbuf *reply_body)
Check ccndid, given a parsed ForwardingEntry.
int ccnd_req_newface (struct ccnd_handle *h, const unsigned char *msg, size_t size, struct ccn_charbuf *reply_body)
Process a newface request for the ccnd internal client.
int ccnd_req_destroyface (struct ccnd_handle *h, const unsigned char *msg, size_t size, struct ccn_charbuf *reply_body)
Process a destroyface request for the ccnd internal client.
static int ccnd_req_prefix_or_self_reg (struct ccnd_handle *h, const unsigned char *msg, size_t size, int selfreg, struct ccn_charbuf *reply_body)
Worker bee for two very similar public functions.
int ccnd_req_prefixreg (struct ccnd_handle *h, const unsigned char *msg, size_t size, struct ccn_charbuf *reply_body)
Process a prefixreg request for the ccnd internal client.
int ccnd_req_selfreg (struct ccnd_handle *h, const unsigned char *msg, size_t size, struct ccn_charbuf *reply_body)
Process a selfreg request for the ccnd internal client.
int ccnd_req_unreg (struct ccnd_handle *h, const unsigned char *msg, size_t size, struct ccn_charbuf *reply_body)
Process an unreg request for the ccnd internal client.
int ccnd_req_strategy (struct ccnd_handle *h, const unsigned char *msg, size_t size, const char *action, struct ccn_charbuf *reply_body)
Process a strategy selection request.
void strategy_init_error (struct ccnd_handle *h, struct strategy_instance *instance, const char *message)
Report a strategy initialization failure.
static struct ccn_indexbuf * get_outbound_faces (struct ccnd_handle *h, struct face *from, const unsigned char *msg, struct ccn_parsed_interest *pi, struct nameprefix_entry *npe)
This is where we consult the interest forwarding table.
static int ie_next_usec (struct ccnd_handle *h, struct interest_entry *ie, ccn_wrappedtime *expiry)
Compute the delay until the next timed action on an interest.
struct pit_face_item * send_interest (struct ccnd_handle *h, struct interest_entry *ie, struct pit_face_item *x, struct pit_face_item *p)
Forward an interest message.
struct nameprefix_entry * get_fib_npe (struct ccnd_handle *h, struct interest_entry *ie)
Find the entry for the longest name prefix that contains forwarding info.
static int strategy_timer (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Implementation detail for strategy_settimer.
void strategy_settimer (struct ccnd_handle *h, struct interest_entry *ie, int usec, enum ccn_strategy_op op)
Schedule a strategy wakeup.
void strategy_getstate (struct ccnd_handle *h, struct ccn_strategy *s, struct nameprefix_state **sst, int k)
Return a pointer to the strategy state records for the name prefix of the given interest entry and up to k-1 parents.
static int do_propagate (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Execute the next timed action on a propagating interest.
static int ccnd_debug_nonce (struct ccnd_handle *h, struct face *face, unsigned char *s)
Append an interest Nonce value that is useful for debugging.
static int ccnd_plain_nonce (struct ccnd_handle *h, struct face *face, unsigned char *s)
Append a random interest Nonce value.
static struct pit_face_item * pfi_create (struct ccnd_handle *h, unsigned faceid, unsigned flags, const unsigned char *nonce, size_t noncesize, struct pit_face_item **pp)
Used in just one place; could go away.
void pfi_set_expiry_from_micros (struct ccnd_handle *h, struct interest_entry *ie, struct pit_face_item *p, unsigned micros)
Set the expiry of the pit face item using a time in microseconds from present.
static void send_tap_interests (struct ccnd_handle *h, struct interest_entry *ie)
Send out a new interest to all the TAP registrations.
static int propagate_interest (struct ccnd_handle *h, struct face *face, unsigned char *msg, struct ccn_parsed_interest *pi, struct nameprefix_entry *npe)
Schedules the propagation of an Interest message.
static struct content_entry * next_child_at_level (struct ccnd_handle *h, struct content_entry *content, int level)
static int drop_nonlocal_interest (struct ccnd_handle *h, struct nameprefix_entry *npe, struct face *face, unsigned char *msg, size_t size)
Check whether the interest should be dropped for local namespace reasons.
static void process_incoming_interest (struct ccnd_handle *h, struct face *face, unsigned char *msg, size_t size)
Process an incoming interest message.
struct strategy_class * strategy_class_from_id (const char *id)
look up a strategy class
struct strategy_instance * create_strategy_instance (struct ccnd_handle *h, struct nameprefix_entry *npe, const struct strategy_class *sclass, const char *parameters)
void remove_strategy_instance (struct ccnd_handle *h, struct nameprefix_entry *npe)
struct strategy_instance * get_strategy_instance (struct ccnd_handle *h, struct nameprefix_entry *npe)
Search the nameprefix tree to find the strategy that is in effect.
static void mark_unsolicited (struct ccnd_handle *h, struct content_entry *content)
Arrange to toss unsolicited content before anything else.
static void set_content_timer (struct ccnd_handle *h, struct content_entry *content, struct ccn_parsed_ContentObject *pco)
Schedules content expiration based on its FreshnessSeconds, and the configured default and limit.
void content_tree_trim (struct ccnd_handle *h)
Discard content as needed to enforce capacity limit.
static void process_incoming_content (struct ccnd_handle *h, struct face *face, unsigned char *wire_msg, size_t wire_size)
Process an arriving ContentObject.
static void ccnd_new_face_msg (struct ccnd_handle *h, struct face *face)
Log a notification that a new datagram face has been created.
static struct sockaddr * scrub_sockaddr (struct sockaddr *addr, socklen_t addrlen, struct sockaddr_in6 *space)
Since struct sockaddr_in6 may contain fields that should not participate in comparison / hash, ensure the undesired fields are zero.
static void process_input_buffer (struct ccnd_handle *h, struct face *face)
Break up data in a face's input buffer buffer into individual messages, and call process_input_message on each one.
static int process_icb_action (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Scheduled event for deferred processing of internal client.
void ccnd_internal_client_has_somthing_to_say (struct ccnd_handle *h)
Schedule the processing of internal client results.
static int handle_send_error (struct ccnd_handle *h, int errnum, struct face *face, const void *data, size_t size)
Handle errors after send() or sendto().
static int sending_fd (struct ccnd_handle *h, struct face *face)
Determine what socket to use to send on a face.
void ccnd_send (struct ccnd_handle *h, struct face *face, const void *data, size_t size)
Send data to the face.
static void prepare_poll_fds (struct ccnd_handle *h)
Set up the array of fd descriptors for the poll(2) call.
void ccnd_run (struct ccnd_handle *h)
Run the main loop of the ccnd.
static void ccnd_reseed (struct ccnd_handle *h)
Reseed our pseudo-random number generator.
static char * ccnd_get_local_sockname (void)
Get the name of our unix-domain socket listener.
static void ccnd_gettime (const struct ccn_gettime *self, struct ccn_timeval *result)
Get the time.
void ccnd_setsockopt_v6only (struct ccnd_handle *h, int fd)
Set IPV6_V6ONLY on a socket.
static const char * af_name (int family)
Translate an address family constant to a string.
static int ccnd_listen_on_wildcards (struct ccnd_handle *h)
Create the standard ipv4 and ipv6 bound ports.
static int ccnd_listen_on_address (struct ccnd_handle *h, const char *addr)
Create a tcp listener and a bound udp socket on the given address.
static int ccnd_listen_on (struct ccnd_handle *h, const char *addrs)
Create listeners or bound udp ports using the given addresses.
static struct ccn_charbuf * ccnd_parse_uri_list (struct ccnd_handle *h, const char *what, const char *uris)
Parse a list of ccnx URIs.
struct ccnd_handle * ccnd_create (const char *progname, ccnd_logger logger, void *loggerdata)
Start a new ccnd instance.
static void ccnd_shutdown_listeners (struct ccnd_handle *h)
Shutdown listeners and bound datagram sockets, leaving connected streams.
void ccnd_destroy (struct ccnd_handle **pccnd)
Destroy the ccnd instance, releasing all associated resources.
Variables
static const char * unlink_this_at_exit = NULL
Name of our unix-domain listener.
Define Documentation
#define CCND_CACHE_MARGIN 10
Allow a few extra entries in the cache to allow for output queuing.
Definition at line 164 of file ccnd.c.
Referenced by process_incoming_content().
#define CCND_MAX_MATCH_PROBES 50000
Maximum number of probes when searching the cache for a match.
Definition at line 171 of file ccnd.c.
Referenced by process_incoming_interest().
#define CCND_WTHZ 1000U
Frequency of wrapped timer.
This should divide 1000000 evenly. Making this too large reduces the maximum supported interest lifetime, and making it too small makes the timekeeping too coarse.
Definition at line 155 of file ccnd.c.
#define WTHZ ((unsigned)(CCND_WTHZ))
Definition at line 158 of file ccnd.c.
Referenced by ccnd_gettime(), do_propagate(), ie_next_usec(), nonce_ok(), pfi_set_expiry_from_lifetime(), pfi_set_expiry_from_micros(), send_interest(), and update_npe_children().
Typedef Documentation
typedef void(* loggerproc)(void *, const char *,...)
Definition at line 1667 of file ccnd.c.
Function Documentation
static int accept_connection (struct ccnd_handle * h, int listener_fd, int listener_flags) [static]
Accept an incoming SOCK_STREAM connection, creating a new face.
This could be, for example, a unix-domain socket, or TCP.
Returns:
fd of new socket, or -1 for an error.
Definition at line 1524 of file ccnd.c.
Referenced by process_input().
static const char* af_name (int family) [static]
Translate an address family constant to a string.
Definition at line 5729 of file ccnd.c.
Referenced by ccnd_listen_on_address(), and ccnd_listen_on_wildcards().
static int age_forwarding (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Age out the old forwarding table entries.
Definition at line 2509 of file ccnd.c.
Referenced by age_forwarding_needed().
static void age_forwarding_needed (struct ccnd_handle * h) [static]
Make sure a call to age_forwarding is scheduled.
Definition at line 2566 of file ccnd.c.
Referenced by ccnd_create().
static void ccn_append_link_stuff (struct ccnd_handle * h, struct face * face, struct ccn_charbuf * c) [static]
Append a sequence number if appropriate.
Definition at line 2222 of file ccnd.c.
Referenced by stuff_and_send().
static void ccn_link_state_init (struct ccnd_handle * h, struct face * face) [static]
Set up to send one sequence number to see it the other side wants to play.
If we don't hear a number from the other side, we won't keep sending them.
Definition at line 2203 of file ccnd.c.
Referenced by register_new_face().
static int ccn_stuff_interest (struct ccnd_handle * h, struct face * face, struct ccn_charbuf * c) [static]
Stuff a PDU with interest messages that will fit.
Returns:
the number of messages that were stuffed.
Definition at line 2188 of file ccnd.c.
Referenced by stuff_and_send().
int ccnd_append_face_guid (struct ccnd_handle * h, struct ccn_charbuf * cb, struct face * face)
Append the guid associated with a face to a charbuf.
Returns:
the length of the appended guid, or -1 for error.
Definition at line 573 of file ccnd.c.
Referenced by append_adjacency_uri(), ccnd_adjacency_offer_or_commit_req(), and ccnd_init_face_guid_cob().
static void ccnd_close_fd (struct ccnd_handle * h, unsigned faceid, int * pfd) [static]
Close an open file descriptor, and grumble about it.
Definition at line 477 of file ccnd.c.
Referenced by finalize_face().
struct ccnd_handle* ccnd_create (const char * progname, ccnd_logger logger, void * loggerdata) [read]
Start a new ccnd instance.
Parameters:
progname - name of program binary, used for locating helpers
logger - logger function
loggerdata - data to pass to logger function
Definition at line 5998 of file ccnd.c.
Referenced by main(), and start_ccnd().
static int ccnd_debug_nonce (struct ccnd_handle * h, struct face * face, unsigned char * s) [static]
Append an interest Nonce value that is useful for debugging.
This does leak some information about the origin of interests, but it also makes it easier to figure out what is happening.
The debug nonce is 12 bytes long. When converted to hexadecimal and broken into fields (big-endian style), it looks like
IIIIII-PPPP-FFFF-SSss-XXXXXX
where IIIIII - first 24 bits of the CCNDID. PPPP - pid of the ccnd. FFFF - 16 low-order bits of the faceid. SSss - local time modulo 256 seconds, with 8 bits of fraction XXXXXX - 24 random bits.
Definition at line 3894 of file ccnd.c.
Referenced by ccnd_create().
void ccnd_destroy (struct ccnd_handle ** pccnd)
Destroy the ccnd instance, releasing all associated resources.
Definition at line 6197 of file ccnd.c.
Referenced by main().
int ccnd_destroy_face (struct ccnd_handle * h, unsigned faceid)
Destroys the face identified by faceid.
Returns:
0 for success, -1 for failure.
Definition at line 2354 of file ccnd.c.
Referenced by ccnd_req_destroyface(), and ccnd_stats_handle_http_connection().
struct face* ccnd_face_from_faceid (struct ccnd_handle * h, unsigned faceid) [read]
Looks up a face based on its faceid.
Get the face handle for a given faceid.
Definition at line 309 of file ccnd.c.
Referenced by adjacency_do_refresh(), adjacency_do_reset(), adjacency_timed_reset(), adjust_builtin_faceattr(), ccnd_answer_by_guid(), ccnd_answer_req(), ccnd_collect_stats(), ccnd_do_solicit(), ccnd_faceattr_strategy_impl(), ccnd_flush_guid_cob(), ccnd_loadsharing_strategy_impl(), ccnd_req_guest(), format_pfi(), incoming_adjacency(), post_face_notice(), schedule_adjacency_negotiation(), and solicit_response().
unsigned ccnd_faceid_from_guid (struct ccnd_handle * h, const unsigned char * guid, size_t size)
Return the faceid associated with the guid.
Definition at line 547 of file ccnd.c.
Referenced by ccnd_answer_by_guid().
void ccnd_forget_face_guid (struct ccnd_handle * h, struct face * face)
Forget the guid associated with a face.
The first byte of face->guid is the length of the actual guid bytes.
Definition at line 588 of file ccnd.c.
Referenced by adjacency_do_reset(), adjacency_timed_reset(), ccnd_answer_req(), check_offer_matches_my_solicit(), and finalize_face().
void ccnd_generate_face_guid (struct ccnd_handle * h, struct face * face, int size, const unsigned char * lo, const unsigned char * hi)
Generate a new guid for a face.
This guid is useful for routing agents, as it gives an unambiguous way to talk about a connection between two nodes.
lo and hi, if not NULL, are exclusive bounds for the generated guid. The size is in bytes, and refers to both the bounds and the result.
Definition at line 620 of file ccnd.c.
Referenced by ccnd_answer_req().
static char* ccnd_get_local_sockname (void) [static]
Get the name of our unix-domain socket listener.
Uses the library to generate the name, using the environment.
Returns:
a newly-allocated nul-terminated string.
Definition at line 5662 of file ccnd.c.
Referenced by ccnd_create().
static int ccnd_getboundsocket (void * dat, struct sockaddr * who, socklen_t wholen) [static]
Get a bound datagram socket.
This is handed to ccn_setup_socket() when setting up a multicast face.
Definition at line 1617 of file ccnd.c.
Referenced by setup_multicast().
static void ccnd_gettime (const struct ccn_gettime * self, struct ccn_timeval * result) [static]
Get the time.
This is used to supply the clock for our scheduled events.
Definition at line 5675 of file ccnd.c.
Referenced by ccnd_create().
void ccnd_internal_client_has_somthing_to_say (struct ccnd_handle * h)
Schedule the processing of internal client results.
This little dance keeps us from destroying an interest entry while we are in the middle of processing it.
Definition at line 5343 of file ccnd.c.
Referenced by ccnd_send(), and send_adjacency_solicit().
static int ccnd_listen_on (struct ccnd_handle * h, const char * addrs) [static]
Create listeners or bound udp ports using the given addresses.
The addresses may be separated by whitespace, commas, or semicolons.
Definition at line 5909 of file ccnd.c.
Referenced by ccnd_create().
static int ccnd_listen_on_address (struct ccnd_handle * h, const char * addr) [static]
Create a tcp listener and a bound udp socket on the given address.
Definition at line 5826 of file ccnd.c.
Referenced by ccnd_listen_on().
static int ccnd_listen_on_wildcards (struct ccnd_handle * h) [static]
Create the standard ipv4 and ipv6 bound ports.
Definition at line 5745 of file ccnd.c.
Referenced by ccnd_listen_on().
int ccnd_n_stale (struct ccnd_handle * h)
Return the number of stale content objects still cached.
This is only used for status reporting
Definition at line 1119 of file ccnd.c.
Referenced by collect_stats_html(), and collect_stats_xml().
static int ccnd_nack (struct ccnd_handle * h, struct ccn_charbuf * reply_body, int errcode, const char * errtext) [static]
Replaces contents of reply_body with a ccnb-encoded StatusResponse.
Returns:
CCN_CONTENT_NACK, or -1 in case of error.
Definition at line 2753 of file ccnd.c.
Referenced by ccnd_req_destroyface(), ccnd_req_newface(), ccnd_req_prefix_or_self_reg(), ccnd_req_strategy(), ccnd_req_unreg(), and check_ccndid().
static void ccnd_new_face_msg (struct ccnd_handle * h, struct face * face) [static]
Log a notification that a new datagram face has been created.
Definition at line 5045 of file ccnd.c.
Referenced by get_dgram_source().
static struct ccn_charbuf* ccnd_parse_uri_list (struct ccnd_handle * h, const char * what, const char * uris) [static, read]
Parse a list of ccnx URIs.
The URIs may be separated by whitespace, commas, or semicolons.
Errors are logged.
Returns:
a newly-allocated charbuf containing nul-terminated URIs; or NULL if no valid URIs are found.
Definition at line 5952 of file ccnd.c.
Referenced by ccnd_create().
static int ccnd_plain_nonce (struct ccnd_handle * h, struct face * face, unsigned char * s) [static]
Append a random interest Nonce value.
For production use, although this uses a simple PRNG.
Definition at line 3916 of file ccnd.c.
Referenced by ccnd_create().
uint32_t ccnd_random (struct ccnd_handle * h)
A PRNG returning 31-bit pseudo-random numbers.
Definition at line 496 of file ccnd.c.
Referenced by ccnd_default_strategy_impl(), ccnd_loadsharing_strategy_impl(), and ccnd_parallel_strategy_impl().
static int ccnd_reg_prefix (struct ccnd_handle * h, const unsigned char * msg, struct ccn_indexbuf * comps, int ncomps, unsigned faceid, int flags, int expires) [static]
Register or update a prefix in the forwarding table (FIB).
Parameters:
h is the ccnd handle.
msg is a ccnb-encoded message containing the name prefix somewhere.
comps contains the delimiting offsets for the name components in msg.
ncomps is the number of relevant components.
faceid indicates which face to forward to.
flags are the forwarding entry flags (CCN_FORW_...), -1 for defaults.
expires tells the remaining lifetime, in seconds.
Returns:
-1 for error, or new flags upon success; the private flag CCN_FORW_REFRESHED indicates a previously existing entry.
Definition at line 2612 of file ccnd.c.
Referenced by ccnd_reg_uri(), and ccnd_req_prefix_or_self_reg().
int ccnd_reg_uri (struct ccnd_handle * h, const char * uri, unsigned faceid, int flags, int expires)
Register a prefix, expressed in the form of a URI.
Returns:
negative value for error, or new face flags for success.
Definition at line 2682 of file ccnd.c.
Referenced by ccnd_internal_client_start(), ccnd_reg_ccnx_ccndid(), ccnd_reg_uri_list(), ccnd_register_adjacency(), ccnd_req_guest(), and ccnd_uri_listen().
void ccnd_reg_uri_list (struct ccnd_handle * h, struct ccn_charbuf * uris, unsigned faceid, int flags, int expires)
Register prefixes, expressed in the form of a list of URIs.
The URIs in the charbuf are each terminated by nul.
Definition at line 2717 of file ccnd.c.
Referenced by register_new_face().
int ccnd_req_destroyface (struct ccnd_handle * h, const unsigned char * msg, size_t size, struct ccn_charbuf * reply_body)
Process a destroyface request for the ccnd internal client.
Parameters:
h is the ccnd handle
msg points to a ccnd-encoded ContentObject containing a FaceInstance in its Content.
size is its size in bytes
reply_body is a buffer to hold the Content of the reply, as a FaceInstance including faceid
Returns:
0 for success, negative for no response, or CCN_CONTENT_NACK to set the response type to NACK.
Is is an error if the face does not exist.
Definition at line 2966 of file ccnd.c.
Referenced by ccnd_answer_req().
int ccnd_req_newface (struct ccnd_handle * h, const unsigned char * msg, size_t size, struct ccn_charbuf * reply_body)
Process a newface request for the ccnd internal client.
Parameters:
h is the ccnd handle
msg points to a ccnd-encoded ContentObject containing a FaceInstance in its Content.
size is its size in bytes
reply_body is a buffer to hold the Content of the reply, as a FaceInstance including faceid
Returns:
0 for success, negative for no response, or CCN_CONTENT_NACK to set the response type to NACK.
Is is permitted for the face to already exist. A newly created face will have no registered prefixes, and so will not receive any traffic.
Definition at line 2819 of file ccnd.c.
Referenced by ccnd_answer_req().
static int ccnd_req_prefix_or_self_reg (struct ccnd_handle * h, const unsigned char * msg, size_t size, int selfreg, struct ccn_charbuf * reply_body) [static]
Worker bee for two very similar public functions.
Definition at line 3024 of file ccnd.c.
Referenced by ccnd_req_prefixreg(), and ccnd_req_selfreg().
int ccnd_req_prefixreg (struct ccnd_handle * h, const unsigned char * msg, size_t size, struct ccn_charbuf * reply_body)
Process a prefixreg request for the ccnd internal client.
Parameters:
h is the ccnd handle
msg points to a ccnd-encoded ContentObject containing a ForwardingEntry in its Content.
size is its size in bytes
reply_body is a buffer to hold the Content of the reply, as a FaceInstance including faceid
Returns:
0 for success, negative for no response, or CCN_CONTENT_NACK to set the response type to NACK.
Definition at line 3123 of file ccnd.c.
Referenced by ccnd_answer_req().
int ccnd_req_selfreg (struct ccnd_handle * h, const unsigned char * msg, size_t size, struct ccn_charbuf * reply_body)
Process a selfreg request for the ccnd internal client.
Parameters:
h is the ccnd handle
msg points to a ccnd-encoded ContentObject containing a ForwardingEntry in its Content.
size is its size in bytes
reply_body is a buffer to hold the Content of the reply, as a ccnb-encoded ForwardingEntry
Returns:
0 for success, negative for no response, or CCN_CONTENT_NACK to set the response type to NACK.
Definition at line 3143 of file ccnd.c.
Referenced by ccnd_answer_req().
int ccnd_req_strategy (struct ccnd_handle * h, const unsigned char * msg, size_t size, const char * action, struct ccn_charbuf * reply_body)
Process a strategy selection request.
This is a request to set, remove, or get the strategy associated with a prefix.
Definition at line 3265 of file ccnd.c.
Referenced by ccnd_answer_req().
int ccnd_req_unreg (struct ccnd_handle * h, const unsigned char * msg, size_t size, struct ccn_charbuf * reply_body)
Process an unreg request for the ccnd internal client.
Parameters:
h is the ccnd handle
msg points to a ccnd-encoded ContentObject containing a ForwardingEntry in its Content.
size is its size in bytes
reply_body is a buffer to hold the Content of the reply, as a ccnb-encoded ForwardingEntry
Returns:
0 for success, negative for no response, or CCN_CONTENT_NACK to set the response type to NACK.
Definition at line 3163 of file ccnd.c.
Referenced by ccnd_answer_req().
static void ccnd_reseed (struct ccnd_handle * h) [static]
Reseed our pseudo-random number generator.
Definition at line 5633 of file ccnd.c.
Referenced by ccnd_create().
void ccnd_run (struct ccnd_handle * h)
Run the main loop of the ccnd.
Definition at line 5582 of file ccnd.c.
Referenced by main(), and start_ccnd().
void ccnd_send (struct ccnd_handle * h, struct face * face, const void * data, size_t size)
Send data to the face.
No direct error result is provided; the face state is updated as needed.
Definition at line 5419 of file ccnd.c.
Referenced by ccnd_stats_handle_http_connection(), send_http_response(), and stuff_and_send().
int ccnd_set_face_guid (struct ccnd_handle * h, struct face * face, const unsigned char * guid, size_t size)
Associate a guid with a face.
The same guid is shared among all the peers that communicate over the face, and no two faces at a node should have the same guid.
Returns:
0 for success, -1 for error.
Definition at line 510 of file ccnd.c.
Referenced by ccnd_generate_face_guid(), check_offer_matches_my_solicit(), and send_adjacency_solicit().
void ccnd_setsockopt_v6only (struct ccnd_handle * h, int fd)
Set IPV6_V6ONLY on a socket.
The handle is used for error reporting.
Definition at line 5713 of file ccnd.c.
Referenced by ccnd_listen_on_address(), and ccnd_listen_on_wildcards().
static void ccnd_shutdown_listeners (struct ccnd_handle * h) [static]
Shutdown listeners and bound datagram sockets, leaving connected streams.
Definition at line 6179 of file ccnd.c.
Referenced by ccnd_destroy().
static struct ccn_charbuf* charbuf_obtain (struct ccnd_handle * h) [static, read]
Obtain a charbuf for short-term use.
Definition at line 239 of file ccnd.c.
Referenced by find_first_match_candidate(), match_interests(), next_child_at_level(), process_incoming_content(), and stuff_and_send().
static void charbuf_release (struct ccnd_handle * h, struct ccn_charbuf * c) [static]
Release a charbuf for reuse.
Definition at line 253 of file ccnd.c.
Referenced by find_first_match_candidate(), match_interests(), next_child_at_level(), process_incoming_content(), and stuff_and_send().
static int check_ccndid (struct ccnd_handle * h, const void * p, size_t sz, struct ccn_charbuf * reply_body) [static]
Check that indicated ccndid matches ours.
Fills reply_body with a StatusResponse in case of no match.
Returns:
0 if OK, or CCN_CONTENT_NACK if not.
Definition at line 2774 of file ccnd.c.
Referenced by check_face_instance_ccndid(), and check_forwarding_entry_ccndid().
static void check_comm_file (struct ccnd_handle * h) [static]
Definition at line 2443 of file ccnd.c.
Referenced by process_input(), reap(), and shutdown_client_fd().
static int check_dgram_faces (struct ccnd_handle * h) [static]
Checks for inactivity on datagram faces.
Returns:
number of faces that have gone away.
Definition at line 2312 of file ccnd.c.
Referenced by reap().
static int check_face_instance_ccndid (struct ccnd_handle * h, struct ccn_face_instance * f, struct ccn_charbuf * reply_body) [static]
Check ccndid, given a face instance.
Definition at line 2786 of file ccnd.c.
Referenced by ccnd_req_destroyface(), and ccnd_req_newface().
static void check_forward_to (struct ccnd_handle * h, struct ccn_indexbuf ** ip) [static]
Remove expired faces from *ip.
Definition at line 2384 of file ccnd.c.
Referenced by check_nameprefix_entries().
static int check_forwarding_entry_ccndid (struct ccnd_handle * h, struct ccn_forwarding_entry * f, struct ccn_charbuf * reply_body) [static]
Check ccndid, given a parsed ForwardingEntry.
Definition at line 2796 of file ccnd.c.
Referenced by ccnd_req_unreg().
static int check_nameprefix_entries (struct ccnd_handle * h) [static]
Ages src info and retires unused nameprefix entries.
Returns:
number that have gone away.
Definition at line 2408 of file ccnd.c.
Referenced by reap().
static enum cq_delay_class choose_content_delay_class (struct ccnd_handle * h, unsigned faceid, int content_flags) [static]
Select the output queue class for a piece of content.
Definition at line 1779 of file ccnd.c.
Referenced by face_send_queue_insert().
static int choose_face_delay (struct ccnd_handle * h, struct face * face, enum cq_delay_class c) [static]
Decide how much to delay the content sent out on a face.
Units are microseconds.
Definition at line 390 of file ccnd.c.
Referenced by content_queue_create().
static void cleanup_at_exit (void) [static]
Main program of ccnd - the CCNx Daemon.
Definition at line 183 of file ccnd.c.
Referenced by handle_fatal_signal(), and unlink_at_exit().
static void close_fd (int * pfd) [static]
Close an open file descriptor quietly.
Definition at line 465 of file ccnd.c.
Referenced by accept_connection().
static int comm_file_ok (void) [static]
Check to see if the unix-domain listener has been unlinked.
Returns:
1 if the file is there, 0 if not.
Definition at line 223 of file ccnd.c.
Referenced by check_comm_file().
static void consume_interest (struct ccnd_handle * h, struct interest_entry * ie) [static]
Consume an interest.
Definition at line 1173 of file ccnd.c.
Referenced by consume_matching_interests(), do_propagate(), and finalize_nameprefix().
static int consume_matching_interests (struct ccnd_handle * h, struct nameprefix_entry * npe, struct content_entry * content, struct ccn_parsed_ContentObject * pc, struct face * face, struct face * content_face) [static]
Consume matching interests given a nameprefix_entry and a piece of content.
If face is not NULL, pay attention only to interests from that face. It is allowed to pass NULL for pc, but if you have a (valid) one it will avoid a re-parse.
Returns:
number of matches found.
Definition at line 1990 of file ccnd.c.
Referenced by match_interests().
static void content_dequeuex (struct ccnd_handle * h, struct content_entry * content) [static]
Remove content from the content expiry queue.
Definition at line 1078 of file ccnd.c.
Referenced by content_preremove(), mark_stale(), mark_unsolicited(), and set_content_timer().
static void content_enqueuex (struct ccnd_handle * h, struct content_entry * content) [static]
Enter content into the content expiry queue according to its staletime.
Definition at line 1039 of file ccnd.c.
Referenced by mark_stale(), mark_unsolicited(), and set_content_timer().
static void content_finalize (struct ccn_nametree * ntree, struct ccny * y) [static]
Finalize content, freeing the raw ccnb before the content_entry is freed.
Definition at line 1158 of file ccnd.c.
Referenced by ccnd_create().
static struct content_entry * content_from_accession (struct ccnd_handle * h, ccn_cookie accession) [static, read]
Convert an accession to its associated content handle.
Returns:
content handle, or NULL if it is no longer available.
Definition at line 894 of file ccnd.c.
Referenced by content_enqueuex(), content_queue_destroy(), and content_sender().
static int content_matches_prefix (struct ccnd_handle * h, struct content_entry * content, struct ccn_charbuf * flat) [static]
Check for a prefix match.
Definition at line 960 of file ccnd.c.
Referenced by process_incoming_interest().
static struct content_entry * content_next (struct ccnd_handle * h, struct content_entry * content) [static, read]
Advance to the next entry in the nametree.
Definition at line 977 of file ccnd.c.
Referenced by process_incoming_interest().
static void content_preremove (struct ccn_nametree * ntree, struct ccny * y) [static]
Dequeue content from expiry queue when removing it from nametree.
Definition at line 1141 of file ccnd.c.
Referenced by ccnd_create().
static struct content_queue* content_queue_create (struct ccnd_handle * h, struct face * face, enum cq_delay_class c) [static, read]
Create a queue for sending content.
Definition at line 409 of file ccnd.c.
Referenced by face_send_queue_insert().
static void content_queue_destroy (struct ccnd_handle * h, struct content_queue ** pq) [static]
Destroy a queue.
Definition at line 434 of file ccnd.c.
Referenced by ccnd_destroy(), and finalize_face().
static int content_sender (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Scheduled event for sending from a queue.
Definition at line 1821 of file ccnd.c.
Referenced by face_send_queue_insert().
void content_tree_trim (struct ccnd_handle * h)
Discard content as needed to enforce capacity limit.
Definition at line 4778 of file ccnd.c.
Referenced by process_incoming_content().
static int create_local_listener (struct ccnd_handle * h, const char * sockname, int backlog) [static]
Create a listener on a unix-domain socket.
Definition at line 1379 of file ccnd.c.
Referenced by ccnd_create().
struct strategy_instance* create_strategy_instance (struct ccnd_handle * h, struct nameprefix_entry * npe, const struct strategy_class * sclass, const char * parameters) [read]
Definition at line 4641 of file ccnd.c.
Referenced by ccnd_req_strategy(), and get_strategy_instance().
static void do_deferred_write (struct ccnd_handle * h, int fd) [static]
Do deferred sends.
These can only happen on streams, after there has been a partial write.
Definition at line 5496 of file ccnd.c.
Referenced by ccnd_run().
static int do_propagate (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Execute the next timed action on a propagating interest.
Definition at line 3725 of file ccnd.c.
Referenced by propagate_interest(), and update_npe_children().
static int drop_nonlocal_interest (struct ccnd_handle * h, struct nameprefix_entry * npe, struct face * face, unsigned char * msg, size_t size) [static]
Check whether the interest should be dropped for local namespace reasons.
Definition at line 4437 of file ccnd.c.
Referenced by process_incoming_interest().
static int enroll_face (struct ccnd_handle * h, struct face * face) [static]
Assigns the faceid for a nacent face, calls register_new_face() if successful.
Definition at line 346 of file ccnd.c.
Referenced by ccnd_create(), get_dgram_source(), and record_connection().
static int establish_min_recv_bufsize (struct ccnd_handle * h, int fd, int minsize) [static]
Adjust socket buffer limit.
Definition at line 1419 of file ccnd.c.
Referenced by setup_multicast().
static int ex_index_cmp (const unsigned char * a, size_t alen, const unsigned char * b, size_t blen) [static]
Definition at line 992 of file ccnd.c.
Referenced by ccnd_create().
unsigned face_faceid (struct face * face)
Accessor for faceid.
Accessors for things a strategy might want to know about a face.
Definition at line 316 of file ccnd.c.
static struct face* face_from_faceid (struct ccnd_handle * h, unsigned faceid) [static, read]
Looks up a face based on its faceid (private).
Definition at line 293 of file ccnd.c.
Referenced by age_forwarding(), ccnd_destroy_face(), ccnd_face_from_faceid(), ccnd_reg_prefix(), ccnd_req_destroyface(), ccnd_req_newface(), ccnd_req_prefix_or_self_reg(), ccnd_req_strategy(), ccnd_req_unreg(), check_forward_to(), choose_content_delay_class(), consume_matching_interests(), content_sender(), do_propagate(), finalize_interest(), get_outbound_faces(), pfi_destroy(), process_incoming_content(), send_interest(), sending_fd(), update_forward_to(), and update_npe_children().
int face_outstanding_interests (struct face * face)
Accessor for number of outstanding interests sent on a face.
Definition at line 334 of file ccnd.c.
Referenced by ccnd_loadsharing_strategy_impl().
int face_pending_interests (struct face * face)
Accessor for number of pending interests received on a face.
Definition at line 325 of file ccnd.c.
static int face_send_queue_insert (struct ccnd_handle * h, struct face * face, struct content_entry * content) [static]
Queue a ContentObject to be sent on a face.
Definition at line 1918 of file ccnd.c.
Referenced by consume_matching_interests(), and process_incoming_interest().
int faceattr_bool_index_from_name (struct ccnd_handle * h, const char * name)
Definition at line 760 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl(), ccnd_loadsharing_strategy_impl(), and faceattr_declare().
static void faceattr_declare (struct ccnd_handle * h, const char * name, int ndx) [static]
Definition at line 851 of file ccnd.c.
Referenced by ccnd_create().
unsigned faceattr_get (struct ccnd_handle * h, struct face * face, int faceattr_index)
Definition at line 831 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl(), and ccnd_loadsharing_strategy_impl().
unsigned faceattr_get_packed (struct ccnd_handle * h, struct face * face)
Definition at line 843 of file ccnd.c.
int faceattr_index_allocate (struct ccnd_handle * h)
Definition at line 766 of file ccnd.c.
int faceattr_index_free (struct ccnd_handle * h, int faceattr_index)
Definition at line 781 of file ccnd.c.
int faceattr_index_from_name (struct ccnd_handle * h, const char * name)
Face attributes.
To help strategies do their work, there is provision for faces to carry a collection of attributes. These have associated values, which can be either boolean or numeric (non-negative integers). Strategies may set and get these values using an attribute index to say which attribute is desired. Some attributes are set by ccnd, based upon things it knows about the face. Others have associated names, and may be set from the outside (using the face managment protocol). Still others are private to strategy implementations, and need not have a name, only a dynamically assigned index.
The first 32 indices (0 through 31) are reserved for single-bit attributes. These may be read all at once using faceattr_get_packed, but are set using the general faceattr_set call. They may also be read using faceattr_get. In the packed form, the attribute with index 0 is stored in the low-order bit, so the bits may be tested using straightforward shifts and masks. After the first 32 single-bit attributes have been created, any additional requests will be fullfulled with attributes capable of carrying numeric values.
Newly created attributes are initialized to 0/false.
Some attributes are created and set by ccnd, reflecting things about faces that may be relevant to the operation of strategies. These are assigned with predeclared indices, so it is not necessary to learn the index from the name at runtime (although this is allowed). All of the built-in single-bit attributes have small indices, and so are accessible using faceattr_get_packed. Macros for corresponding bit masks are also provided.
Definition at line 754 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl(), faceattr_declare(), and faceattr_index_allocate().
static int faceattr_index_lookup (struct ccnd_handle * h, const char * name, int singlebit) [static]
Definition at line 720 of file ccnd.c.
Referenced by faceattr_bool_index_from_name(), and faceattr_index_from_name().
const char* faceattr_next_name (struct ccnd_handle * h, const char * name)
Stateless enumerator for face attribute names.
Call with NULL to get the first name. Returns NULL after the last name. The order is unspecified. Generated names are provided for private attrs.
Definition at line 864 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl().
int faceattr_set (struct ccnd_handle * h, struct face * face, int faceattr_index, unsigned value)
Definition at line 798 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl(), and ccnd_loadsharing_strategy_impl().
static unsigned faceid_from_fd (struct ccnd_handle * h, int fd) [static]
Get the faceid associated with a file descriptor.
Returns:
the faceid, or CCN_NOFACEID.
Definition at line 1659 of file ccnd.c.
Referenced by setup_multicast().
static void finalize_face (struct hashtb_enumerator * e) [static]
Clean up when a face is being destroyed.
This is called when an entry is deleted from one of the hash tables that keep track of faces.
Definition at line 675 of file ccnd.c.
Referenced by ccnd_create().
static void finalize_guest (struct hashtb_enumerator * e) [static]
Clean up a guest_entry when it is removed from its hash table.
Definition at line 1369 of file ccnd.c.
Referenced by ccnd_create().
static void finalize_interest (struct hashtb_enumerator * e) [static]
Clean up an interest_entry when it is removed from its hash table.
Definition at line 1230 of file ccnd.c.
Referenced by ccnd_create().
static void finalize_nameprefix (struct hashtb_enumerator * e) [static]
Clean up a name prefix entry when it is removed from the hash table.
Definition at line 1191 of file ccnd.c.
Referenced by ccnd_create().
static void finalize_nonce (struct hashtb_enumerator * e) [static]
Clean up a nonce_entry when it is removed from its hash table.
Definition at line 1353 of file ccnd.c.
Referenced by ccnd_create().
static struct content_entry* find_first_match_candidate (struct ccnd_handle * h, const unsigned char * interest_msg, const struct ccn_parsed_interest * pi) [static, read]
Find the first candidate that might match the given interest.
Definition at line 909 of file ccnd.c.
Referenced by process_incoming_interest().
static struct face * get_dgram_source (struct ccnd_handle * h, struct face * face, struct sockaddr * addr, socklen_t addrlen, int why) [static, read]
Get (or create) the face associated with a given sockaddr.
Definition at line 5107 of file ccnd.c.
Referenced by ccnd_req_newface(), and process_input().
struct nameprefix_entry* get_fib_npe (struct ccnd_handle * h, struct interest_entry * ie) [read]
Find the entry for the longest name prefix that contains forwarding info.
Definition at line 3655 of file ccnd.c.
Referenced by send_tap_interests().
static struct ccn_indexbuf* get_outbound_faces (struct ccnd_handle * h, struct face * from, const unsigned char * msg, struct ccn_parsed_interest * pi, struct nameprefix_entry * npe) [static, read]
This is where we consult the interest forwarding table.
Parameters:
h is the ccnd handle
from is the handle for the originating face (may be NULL).
msg points to the ccnb-encoded interest message
pi must be the parse information for msg
npe should be the result of the prefix lookup
Returns:
Newly allocated set of outgoing faceids (never NULL)
Definition at line 3498 of file ccnd.c.
Referenced by propagate_interest(), and update_npe_children().
struct strategy_instance* get_strategy_instance (struct ccnd_handle * h, struct nameprefix_entry * npe) [read]
Search the nameprefix tree to find the strategy that is in effect.
Definition at line 4692 of file ccnd.c.
Referenced by ccnd_req_strategy(), do_propagate(), and strategy_callout().
static void handle_fatal_signal (int sig) [static]
Definition at line 192 of file ccnd.c.
Referenced by unlink_at_exit().
static int handle_send_error (struct ccnd_handle * h, int errnum, struct face * face, const void * data, size_t size) [static]
Handle errors after send() or sendto().
Returns:
-1 if error has been dealt with, or 0 to defer sending.
Definition at line 5353 of file ccnd.c.
Referenced by ccnd_send().
static int ie_next_usec (struct ccnd_handle * h, struct interest_entry * ie, ccn_wrappedtime * expiry) [static]
Compute the delay until the next timed action on an interest.
Definition at line 3558 of file ccnd.c.
Referenced by propagate_interest().
static struct ccn_indexbuf* indexbuf_obtain (struct ccnd_handle * h) [static, read]
Obtain an indexbuf for short-term use.
Definition at line 266 of file ccnd.c.
Referenced by match_interests(), process_incoming_content(), and process_incoming_interest().
static void indexbuf_release (struct ccnd_handle * h, struct ccn_indexbuf * c) [static]
Release an indexbuf for reuse.
Definition at line 280 of file ccnd.c.
Referenced by match_interests(), process_incoming_content(), and process_incoming_interest().
static void init_face_flags (struct ccnd_handle * h, struct face * face, int setflags) [static]
Initialize the face flags based upon the addr information and the provided explicit setflags.
Definition at line 1444 of file ccnd.c.
Referenced by get_dgram_source(), and record_connection().
static int is_pending_on (struct ccnd_handle * h, struct interest_entry * ie, unsigned faceid) [static]
Return true iff the interest is pending on the given face.
Definition at line 1967 of file ccnd.c.
Referenced by consume_matching_interests().
static int is_stale (struct ccnd_handle * h, struct content_entry * content) [static]
Check to see whether content is stale.
This depends on h->sec being more or less up to date, but that should be true pretty anytime we care about staleness.
Definition at line 1107 of file ccnd.c.
Referenced by content_tree_trim(), mark_stale(), process_incoming_content(), and process_incoming_interest().
static void link_interest_entry_to_nameprefix (struct ccnd_handle * h, struct interest_entry * ie, struct nameprefix_entry * npe) [static]
Link an interest to its name prefix entry.
Definition at line 1215 of file ccnd.c.
Referenced by propagate_interest().
static struct face* make_connection (struct ccnd_handle * h, struct sockaddr * who, socklen_t wholen, int setflags) [static, read]
Make an outbound stream connection.
Definition at line 1551 of file ccnd.c.
Referenced by ccnd_req_newface().
static void mark_stale (struct ccnd_handle * h, struct content_entry * content) [static]
Mark content as stale.
Definition at line 4726 of file ccnd.c.
Referenced by content_tree_trim(), and process_incoming_interest().
static void mark_unsolicited (struct ccnd_handle * h, struct content_entry * content) [static]
Arrange to toss unsolicited content before anything else.
Definition at line 4739 of file ccnd.c.
Referenced by process_incoming_content().
static int match_interests (struct ccnd_handle * h, struct content_entry * content, struct ccn_parsed_ContentObject * pc, struct face * face, struct face * from_face) [static]
Find and consume interests that match given content.
Schedules the sending of the content. If face is not NULL, pay attention only to interests from that face. It is allowed to pass NULL for pc, but if you have a (valid) one it will avoid a re-parse. For new content, from_face is the source; for old content, from_face is NULL.
Returns:
number of matches, or -1 if the new content should be dropped.
Definition at line 2043 of file ccnd.c.
Referenced by process_incoming_content(), and process_incoming_interest().
static int nameprefix_seek (struct ccnd_handle * h, struct hashtb_enumerator * e, const unsigned char * msg, struct ccn_indexbuf * comps, int ncomps) [static]
Creates a nameprefix entry if it does not already exist, together with all of its parents.
Definition at line 4343 of file ccnd.c.
Referenced by ccnd_reg_prefix(), ccnd_req_strategy(), and process_incoming_interest().
static struct content_entry* next_child_at_level (struct ccnd_handle * h, struct content_entry * content, int level) [static, read]
Definition at line 4391 of file ccnd.c.
Referenced by process_incoming_interest().
static int nonce_ok (struct ccnd_handle * h, struct face * face, const unsigned char * interest_msg, struct ccn_parsed_interest * pi, const unsigned char * nonce, size_t noncesize) [static]
Look for duplication of interest nonces.
If nonce is NULL and the interest message has a nonce, the latter will be used.
The nonce will be added to the nonce table if it is not already there. Some expired entries may be trimmed.
Returns:
0 if a duplicate, unexpired nonce exists, 1 if nonce is new, 2 if duplicate is from originating face, or 3 if the interest does not have a nonce. Negative means error.
Definition at line 1281 of file ccnd.c.
Referenced by process_incoming_interest(), and propagate_interest().
static struct pit_face_item * pfi_copy_nonce (struct ccnd_handle * h, struct interest_entry * ie, struct pit_face_item * p, const struct pit_face_item * src) [static, read]
Copy a nonce from src into p.
Returns:
p (or its replacement)
Definition at line 4117 of file ccnd.c.
Referenced by send_interest().
static struct pit_face_item* pfi_create (struct ccnd_handle * h, unsigned faceid, unsigned flags, const unsigned char * nonce, size_t noncesize, struct pit_face_item ** pp) [static, read]
Used in just one place; could go away.
Definition at line 3941 of file ccnd.c.
Referenced by pfi_set_nonce().
static void pfi_destroy (struct ccnd_handle * h, struct interest_entry * ie, struct pit_face_item * p) [static]
Remove the pit face item from the interest entry.
Definition at line 3968 of file ccnd.c.
Referenced by do_propagate(), and pfi_set_nonce().
static int pfi_nonce_matches (struct pit_face_item * p, const unsigned char * nonce, size_t size) [static]
Return true iff the nonce in p matches the given one.
Definition at line 4099 of file ccnd.c.
Referenced by pfi_unique_nonce().
static struct pit_face_item * pfi_seek (struct ccnd_handle * h, struct interest_entry * ie, unsigned faceid, unsigned pfi_flag) [static, read]
Find the pit face item with the given flag set, or create it if not present.
New items are appended to the end of the list
Definition at line 3998 of file ccnd.c.
Referenced by propagate_interest(), and update_npe_children().
static void pfi_set_expiry_from_lifetime (struct ccnd_handle * h, struct interest_entry * ie, struct pit_face_item * p, intmax_t lifetime) [static]
Set the expiry of the pit face item based upon an interest lifetime.
lifetime is in the units specified by the CCNx protocal - 1/4096 sec
Also sets the renewed timestamp to now.
Definition at line 4026 of file ccnd.c.
Referenced by propagate_interest().
void pfi_set_expiry_from_micros (struct ccnd_handle * h, struct interest_entry * ie, struct pit_face_item * p, unsigned micros)
Set the expiry of the pit face item using a time in microseconds from present.
Does not set the renewed timestamp.
Definition at line 4053 of file ccnd.c.
Referenced by ccnd_default_strategy_impl().
static struct pit_face_item * pfi_set_nonce (struct ccnd_handle * h, struct interest_entry * ie, struct pit_face_item * p, const unsigned char * nonce, size_t noncesize) [static, read]
Set the nonce in a pit face item.
Returns:
the replacement value, which is p unless the nonce will not fit.
Definition at line 4068 of file ccnd.c.
Referenced by pfi_copy_nonce(), and propagate_interest().
static int pfi_unique_nonce (struct ccnd_handle * h, struct interest_entry * ie, struct pit_face_item * p) [static]
True iff the nonce in p does not occur in any of the other items of the entry.
Definition at line 4128 of file ccnd.c.
Referenced by propagate_interest().
static void prepare_poll_fds (struct ccnd_handle * h) [static]
Set up the array of fd descriptors for the poll(2) call.
Arrange the array so that multicast receivers are early, so that if the same packet arrives on both a multicast socket and a normal socket, we will count is as multicast.
Definition at line 5551 of file ccnd.c.
Referenced by ccnd_run().
static int process_icb_action (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Scheduled event for deferred processing of internal client.
Definition at line 5322 of file ccnd.c.
Referenced by ccnd_internal_client_has_somthing_to_say().
static void process_incoming_content (struct ccnd_handle * h, struct face * face, unsigned char * wire_msg, size_t wire_size) [static]
Process an arriving ContentObject.
Parse the ContentObject and discard if it is not well-formed.
Compute the digest.
Look it up in the content store. It it is already there, but is stale, make it fresh again. If it is not there, add it.
Find the matching pending interests in the PIT and consume them, queueing the ContentObject to be sent on the associated faces. If no matches were found and the content object was new, remove it from the store.
XXX - the change to staleness should also not happen if there was no matching PIT entry.
Definition at line 4830 of file ccnd.c.
Referenced by load_policy(), process_input_message(), r_init_map_and_process_file(), r_proto_expect_content(), r_sync_local_store(), and r_sync_upcall_store().
static void process_incoming_interest (struct ccnd_handle * h, struct face * face, unsigned char * msg, size_t size) [static]
Process an incoming interest message.
Parse the Interest and discard if it does not parse. Check for correct scope (a scope 0 or scope 1 interest should never arrive on an external face). Check for a duplicated Nonce, discard if it has been seen before. Look up the name prefix. Check for a local namespace and discard if an interest in a local namespace arrives from outside. Consult the content store. If a suitable matching ContentObject is found, prepare to send it, consuming this interest and any pending interests on that face that also match this object. Otherwise, initiate propagation of the interest.
Definition at line 4467 of file ccnd.c.
Referenced by process_input_message().
static int process_incoming_link_message (struct ccnd_handle * h, struct face * face, enum ccn_dtag dtag, unsigned char * msg, size_t size) [static]
Process an incoming link message.
Definition at line 2243 of file ccnd.c.
Referenced by process_input_message().
static void process_input (struct ccnd_handle * h, int fd) [static]
Process the input from a socket.
The socket has been found ready for input by the poll call. Decide what face it corresponds to, and after checking for exceptional cases, receive data, parse it into ccnb-encoded messages, and call process_input_message for each one.
Definition at line 5189 of file ccnd.c.
Referenced by ccnd_run().
static void process_input_buffer (struct ccnd_handle * h, struct face * face) [static]
Break up data in a face's input buffer buffer into individual messages, and call process_input_message on each one.
This is used to handle things originating from the internal client - its output is input for face 0.
Definition at line 5153 of file ccnd.c.
Referenced by process_internal_client_buffer().
static void process_input_message (struct ccnd_handle * h, struct face * face, unsigned char * msg, size_t size, int pdu_ok) [static]
Process an incoming message.
This is where we decide whether we have an Interest message, a ContentObject, or something else.
Definition at line 4977 of file ccnd.c.
Referenced by process_input(), and process_input_buffer().
static void process_internal_client_buffer (struct ccnd_handle * h) [static]
Process messages from our internal client.
The internal client's output is input to us.
Definition at line 5305 of file ccnd.c.
Referenced by ccnd_run(), check_dgram_faces(), and process_icb_action().
static int propagate_interest (struct ccnd_handle * h, struct face * face, unsigned char * msg, struct ccn_parsed_interest * pi, struct nameprefix_entry * npe) [static]
Schedules the propagation of an Interest message.
Definition at line 4177 of file ccnd.c.
Referenced by process_incoming_interest().
static unsigned randomize_content_delay (struct ccnd_handle * h, struct content_queue * q) [static]
Pick a randomized delay for sending.
This is primarily for multicast and similar broadcast situations, where we may see the content being sent by somebody else. If that is the case, we will avoid sending our copy as well.
Definition at line 1802 of file ccnd.c.
Referenced by content_sender(), and face_send_queue_insert().
static int reap (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Scheduled reap event for retiring expired structures.
Definition at line 2456 of file ccnd.c.
Referenced by reap_needed().
static void reap_needed (struct ccnd_handle * h, int init_delay_usec) [static]
Definition at line 2476 of file ccnd.c.
Referenced by ccnd_create().
static struct face * record_connection (struct ccnd_handle * h, int fd, struct sockaddr * who, socklen_t wholen, int setflags) [static, read]
Make a new face entered in the faces_by_fd table.
Definition at line 1483 of file ccnd.c.
Referenced by accept_connection(), ccnd_getboundsocket(), ccnd_listen_on_address(), ccnd_listen_on_wildcards(), create_local_listener(), make_connection(), and setup_multicast().
static void register_new_face (struct ccnd_handle * h, struct face * face) [static]
Called when a face is first created, and (perhaps) a second time in the case that a face transitions from the undecided state.
Definition at line 2735 of file ccnd.c.
Referenced by enroll_face(), and process_input_message().
static int remove_content (struct ccnd_handle * h, struct content_entry * content) [static]
Remove a content object from the store.
Definition at line 2486 of file ccnd.c.
Referenced by content_tree_trim(), process_incoming_content(), and process_incoming_interest().
void remove_strategy_instance (struct ccnd_handle * h, struct nameprefix_entry * npe)
Definition at line 4673 of file ccnd.c.
Referenced by ccnd_req_strategy(), create_strategy_instance(), and finalize_nameprefix().
static struct sockaddr* scrub_sockaddr (struct sockaddr * addr, socklen_t addrlen, struct sockaddr_in6 * space) [static, read]
Since struct sockaddr_in6 may contain fields that should not participate in comparison / hash, ensure the undesired fields are zero.
Per RFC 3493, sin6_flowinfo is zeroed.
Parameters:
addr is the sockaddr (any family)
addrlen is its length
space points to a buffer that may be used for the result.
Returns:
either the original addr or a pointer to a scrubbed copy.
Definition at line 5084 of file ccnd.c.
Referenced by get_dgram_source().
static struct ccn_forwarding* seek_forwarding (struct ccnd_handle * h, struct nameprefix_entry * npe, unsigned faceid) [static, read]
Look up a forwarding entry, creating it if it is not there.
Definition at line 2579 of file ccnd.c.
Referenced by ccnd_reg_prefix().
static void send_content (struct ccnd_handle * h, struct face * face, struct content_entry * content) [static]
Send a ContentObject.
This is after it has worked its way through the queue; update the meters and stuff the packet as appropriate.
Definition at line 1759 of file ccnd.c.
Referenced by content_sender().
struct pit_face_item* send_interest (struct ccnd_handle * h, struct interest_entry * ie, struct pit_face_item * x, struct pit_face_item * p) [read]
Forward an interest message.
x is downstream (the interest came from x). p is upstream (the interest is to be forwarded to p).
Returns:
p (or its reallocated replacement).
Definition at line 3612 of file ccnd.c.
Referenced by ccnd_default_strategy_impl(), do_propagate(), and send_tap_interests().
static void send_tap_interests (struct ccnd_handle * h, struct interest_entry * ie) [static]
Send out a new interest to all the TAP registrations.
Definition at line 4148 of file ccnd.c.
Referenced by propagate_interest().
static int sending_fd (struct ccnd_handle * h, struct face * face) [static]
Determine what socket to use to send on a face.
For streams, this just returns the associated fd.
For datagrams, one fd may be in use for many faces, so we need to find the right one to use.
This is not as smart as it should be for situations where CCND_LISTEN_ON has been specified.
Definition at line 5386 of file ccnd.c.
Referenced by ccnd_send().
static void set_content_timer (struct ccnd_handle * h, struct content_entry * content, struct ccn_parsed_ContentObject * pco) [static]
Schedules content expiration based on its FreshnessSeconds, and the configured default and limit.
Definition at line 4751 of file ccnd.c.
Referenced by process_incoming_content().
static struct face* setup_multicast (struct ccnd_handle * h, struct ccn_face_instance * face_instance, struct sockaddr * who, socklen_t wholen) [static, read]
Set up a multicast face.
Definition at line 1673 of file ccnd.c.
Referenced by ccnd_req_newface().
static void shutdown_client_fd (struct ccnd_handle * h, int fd) [static]
Close a socket, destroying the associated face.
Definition at line 1724 of file ccnd.c.
Referenced by ccnd_destroy_face(), ccnd_run(), do_deferred_write(), and process_input().
static void strategy_callout (struct ccnd_handle * h, struct interest_entry * ie, enum ccn_strategy_op op, unsigned faceid) [static]
Call the strategy routine.
Definition at line 4711 of file ccnd.c.
Referenced by consume_matching_interests(), do_propagate(), propagate_interest(), and strategy_timer().
struct strategy_class* strategy_class_from_id (const char * id) [read]
look up a strategy class
Definition at line 4629 of file ccnd.c.
Referenced by ccnd_req_strategy(), ccnd_trace_strategy_impl(), and get_strategy_instance().
void strategy_getstate (struct ccnd_handle * h, struct ccn_strategy * s, struct nameprefix_state ** sst, int k)
Return a pointer to the strategy state records for the name prefix of the given interest entry and up to k-1 parents.
The sst array is filled in; NULL values are provided as needed. The item sst[0] corresponds with the name inside the interest, and is never NULL unless s is NULL. The remaining entries are for successively shorter prefixes.
Definition at line 3707 of file ccnd.c.
Referenced by ccnd_default_strategy_impl().
void strategy_init_error (struct ccnd_handle * h, struct strategy_instance * instance, const char * message)
Report a strategy initialization failure.
Note a strategy initialization error.
Definition at line 3413 of file ccnd.c.
Referenced by ccnd_faceattr_strategy_impl(), and ccnd_trace_strategy_impl().
void strategy_settimer (struct ccnd_handle * h, struct interest_entry * ie, int usec, enum ccn_strategy_op op)
Schedule a strategy wakeup.
Any previously wakeup will be cancelled.
Definition at line 3690 of file ccnd.c.
Referenced by ccnd_default_strategy_impl().
static int strategy_timer (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Implementation detail for strategy_settimer.
Definition at line 3667 of file ccnd.c.
Referenced by strategy_settimer().
static void stuff_and_send (struct ccnd_handle * h, struct face * face, const unsigned char * data1, size_t size1, const unsigned char * data2, size_t size2, const char * tag, int lineno) [static]
Send a message in a PDU, possibly stuffing other interest messages into it.
The message may be in two pieces.
Definition at line 2094 of file ccnd.c.
Referenced by send_content(), and send_interest().
static int stuff_link_check (struct ccnd_handle * h, struct face * face, struct ccn_charbuf * c) [static]
Append a link-check interest if appropriate.
Returns:
the number of messages that were stuffed.
Definition at line 2143 of file ccnd.c.
Referenced by ccn_stuff_interest().
static void unlink_at_exit (const char * path) [static]
Record the name of the unix-domain listener.
Sets up signal handlers in case we are stopping due to a signal.
Definition at line 204 of file ccnd.c.
Referenced by create_local_listener().
static void update_ex_index (struct ccnd_handle * h, int staletime, ccn_cookie c) [static]
Update the index to the expiry queue.
This index is used for quickly finding the last entry in the expiry queue that has a staletime less than or equal to the given value.
Definition at line 1008 of file ccnd.c.
Referenced by content_dequeuex(), and content_enqueuex().
static void update_forward_to (struct ccnd_handle * h, struct nameprefix_entry * npe) [static]
Set up forward_to list for a name prefix entry.
Recomputes the contents of npe->forward_to and npe->flags from forwarding lists of npe and all of its ancestors.
Also updates the tap, strategy_ix, and strategy_up fields of npe.
Definition at line 3433 of file ccnd.c.
Referenced by drop_nonlocal_interest(), get_outbound_faces(), and match_interests().
static void update_npe_children (struct ccnd_handle * h, struct nameprefix_entry * npe, unsigned faceid) [static]
We have a FIB change - accelerate forwarding of existing interests.
Definition at line 4280 of file ccnd.c.
Referenced by ccnd_reg_prefix().
static int wt_compare (ccn_wrappedtime a, ccn_wrappedtime b) [static]
Compare two wrapped time values.
Returns:
negative if a < b, 0 if a == b, positive if a > b
Definition at line 3931 of file ccnd.c.
Referenced by do_propagate(), nonce_ok(), propagate_interest(), and update_npe_children().
Variable Documentation
const char* unlink_this_at_exit = NULL [static]
Name of our unix-domain listener.
This tiny bit of global state is needed so that the unix-domain listener can be removed at shutdown.
Definition at line 180 of file ccnd.c.
Referenced by check_comm_file(), cleanup_at_exit(), comm_file_ok(), and unlink_at_exit().