Content-Centric Networking in C: ccnr/ccnr_sendq.c File Reference
ccnr_sendq.c File Reference
Part of ccnr - CCNx Repository Daemon.
Functions
static int choose_face_delay (struct ccnr_handle *h, struct fdholder *fdholder, enum cq_delay_class c)
static struct content_queue * content_queue_create (struct ccnr_handle *h, struct fdholder *fdholder, enum cq_delay_class c)
PUBLIC void r_sendq_content_queue_destroy (struct ccnr_handle *h, struct content_queue **pq)
static enum cq_delay_class choose_content_delay_class (struct ccnr_handle *h, unsigned filedesc, int content_flags)
static unsigned randomize_content_delay (struct ccnr_handle *h, struct content_queue *q)
static int content_sender (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
PUBLIC int r_sendq_face_send_queue_insert (struct ccnr_handle *h, struct fdholder *fdholder, struct content_entry *content)
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_sendq.c.
Function Documentation
static enum cq_delay_class choose_content_delay_class (struct ccnr_handle * h, unsigned filedesc, int content_flags) [static]
Definition at line 113 of file ccnr_sendq.c.
Referenced by r_sendq_face_send_queue_insert().
static int choose_face_delay (struct ccnr_handle * h, struct fdholder * fdholder, enum cq_delay_class c) [static]
Definition at line 65 of file ccnr_sendq.c.
Referenced by content_queue_create().
static struct content_queue* content_queue_create (struct ccnr_handle * h, struct fdholder * fdholder, enum cq_delay_class c) [static, read]
Definition at line 75 of file ccnr_sendq.c.
Referenced by r_sendq_face_send_queue_insert().
static int content_sender (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 135 of file ccnr_sendq.c.
Referenced by r_sendq_face_send_queue_insert().
PUBLIC void r_sendq_content_queue_destroy (struct ccnr_handle * h, struct content_queue ** pq)
Definition at line 97 of file ccnr_sendq.c.
Referenced by r_io_shutdown_client_fd().
PUBLIC int r_sendq_face_send_queue_insert (struct ccnr_handle * h, struct fdholder * fdholder, struct content_entry * content)
Definition at line 222 of file ccnr_sendq.c.
Referenced by r_match_consume_matching_interests(), and r_proto_answer_req().
static unsigned randomize_content_delay (struct ccnr_handle * h, struct content_queue * q) [static]
Definition at line 119 of file ccnr_sendq.c.
Referenced by content_sender(), and r_sendq_face_send_queue_insert().