Content-Centric Networking in C: ccnr/ccnr_dispatch.h File Reference
ccnr_dispatch.h File Reference
Part of ccnr - CCNx Repository Daemon.
Functions
void r_dispatch_run (struct ccnr_handle *h)
Run the main loop of the ccnr.
void r_dispatch_process_internal_client_buffer (struct ccnr_handle *h)
struct content_entry * process_incoming_content (struct ccnr_handle *h, struct fdholder *fdholder, unsigned char *msg, size_t size, off_t *offsetp)
void r_dispatch_process_input (struct ccnr_handle *h, int fd)
Process the input from a socket or file.
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_dispatch.h.
Function Documentation
struct content_entry* process_incoming_content (struct ccnr_handle * h, struct fdholder * fdholder, unsigned char * msg, size_t size, off_t * offsetp) [read]
Definition at line 1268 of file ccnr_store.c.
void r_dispatch_process_input (struct ccnr_handle * h, int fd)
Process the input from a socket or file.
The fd has been found ready for input by the poll call. Decide what fdholder it corresponds to, and after checking for exceptional cases, receive data, parse it into ccnb-encoded messages, and call process_input_message for each one.
Definition at line 161 of file ccnr_dispatch.c.
Referenced by r_dispatch_run(), and r_init_create().
void r_dispatch_process_internal_client_buffer (struct ccnr_handle * h)
Definition at line 276 of file ccnr_dispatch.c.
void r_dispatch_run (struct ccnr_handle * h)
Run the main loop of the ccnr.
Definition at line 292 of file ccnr_dispatch.c.
Referenced by main(), and start_ccnr().