Content-Centric Networking in C: ccnr/ccnr_stats.h File Reference
ccnr_stats.h File Reference
Part of ccnr - CCNx Repository Daemon.
Functions
void ccnr_meter_bump (struct ccnr_handle *h, struct ccnr_meter *m, unsigned amt)
Count something (messages, packets, bytes), and roll up some kind of statistics on it.
void ccnr_meter_destroy (struct ccnr_meter **pm)
Destroy a separately allocated meter.
void ccnr_meter_init (struct ccnr_handle *h, struct ccnr_meter *m, const char *what)
Initialize a meter.
struct ccnr_meter * ccnr_meter_create (struct ccnr_handle *h, const char *what)
create and initialize separately allocated meter.
uintmax_t ccnr_meter_total (struct ccnr_meter *m)
Return the grand total for a metered quantity.
unsigned ccnr_meter_rate (struct ccnr_handle *h, struct ccnr_meter *m)
Return the average rate (units per second) of a metered quantity.
int ccnr_stats_handle_http_connection (struct ccnr_handle *h, struct fdholder *fdholder)
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_stats.h.
Function Documentation
void ccnr_meter_bump (struct ccnr_handle * h, struct ccnr_meter * m, unsigned amt)
Count something (messages, packets, bytes), and roll up some kind of statistics on it.
Definition at line 667 of file ccnr_stats.c.
Referenced by ccnr_meter_init(), ccnr_meter_rate(), process_incoming_content(), r_dispatch_process_input(), r_dispatch_process_internal_client_buffer(), r_io_send(), and r_link_send_content().
struct ccnr_meter* ccnr_meter_create (struct ccnr_handle * h, const char * what) [read]
create and initialize separately allocated meter.
Definition at line 624 of file ccnr_stats.c.
Referenced by r_io_enroll_face().
void ccnr_meter_destroy (struct ccnr_meter ** pm)
Destroy a separately allocated meter.
Definition at line 638 of file ccnr_stats.c.
Referenced by r_io_shutdown_client_fd().
void ccnr_meter_init (struct ccnr_handle * h, struct ccnr_meter * m, const char * what)
Initialize a meter.
Definition at line 650 of file ccnr_stats.c.
Referenced by ccnr_meter_create().
unsigned ccnr_meter_rate (struct ccnr_handle * h, struct ccnr_meter * m)
Return the average rate (units per second) of a metered quantity.
m may be NULL.
Definition at line 694 of file ccnr_stats.c.
Referenced by collect_face_meter_html(), and collect_meter_xml().
uintmax_t ccnr_meter_total (struct ccnr_meter * m)
Return the grand total for a metered quantity.
m may be NULL.
Definition at line 711 of file ccnr_stats.c.
Referenced by collect_meter_xml(), and r_store_reindexing().
int ccnr_stats_handle_http_connection (struct ccnr_handle * h, struct fdholder * fdholder)
Definition at line 103 of file ccnr_stats.c.
Referenced by r_dispatch_process_input().