Content-Centric Networking in C: ccnr/ccnr_util.c File Reference
ccnr_util.c File Reference
Part of ccnr - CCNx Repository Daemon.
Functions
PUBLIC struct ccn_charbuf * r_util_charbuf_obtain (struct ccnr_handle *h)
PUBLIC void r_util_charbuf_release (struct ccnr_handle *h, struct ccn_charbuf *c)
PUBLIC struct ccn_indexbuf * r_util_indexbuf_obtain (struct ccnr_handle *h)
PUBLIC void r_util_indexbuf_release (struct ccnr_handle *h, struct ccn_indexbuf *c)
PUBLIC void r_util_reseed (struct ccnr_handle *h)
PUBLIC void r_util_gettime (const struct ccn_gettime *self, struct ccn_timeval *result)
PUBLIC int r_util_timecmp (long secA, unsigned usecA, long secB, unsigned usecB)
PUBLIC intmax_t r_util_segment_from_component (const unsigned char *ccnb, size_t start, size_t stop)
int r_util_name_comp_compare (const unsigned char *data, const struct ccn_indexbuf *indexbuf, unsigned int i, const void *buf, size_t length)
Compare a name component at index i to bytes in buf and return 0 if they are equal length and equal value.
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_util.c.
Function Documentation
PUBLIC struct ccn_charbuf* r_util_charbuf_obtain (struct ccnr_handle * h) [read]
Definition at line 60 of file ccnr_util.c.
Referenced by r_link_stuff_and_send(), and r_sync_notify_content().
PUBLIC void r_util_charbuf_release (struct ccnr_handle * h, struct ccn_charbuf * c)
Definition at line 71 of file ccnr_util.c.
Referenced by r_link_stuff_and_send(), and r_sync_notify_content().
PUBLIC void r_util_gettime (const struct ccn_gettime * self, struct ccn_timeval * result)
Definition at line 125 of file ccnr_util.c.
Referenced by r_init_create().
PUBLIC struct ccn_indexbuf* r_util_indexbuf_obtain (struct ccnr_handle * h) [read]
Definition at line 81 of file ccnr_util.c.
Referenced by r_lookup().
PUBLIC void r_util_indexbuf_release (struct ccnr_handle * h, struct ccn_indexbuf * c)
Definition at line 92 of file ccnr_util.c.
Referenced by r_lookup().
int r_util_name_comp_compare (const unsigned char * data, const struct ccn_indexbuf * indexbuf, unsigned int i, const void * buf, size_t length)
Compare a name component at index i to bytes in buf and return 0 if they are equal length and equal value.
In the case of inequality, a negative or positive value is returned, according to the canonical ordering of names.
Definition at line 173 of file ccnr_util.c.
Referenced by r_proto_answer_req(), and r_proto_start_write().
PUBLIC void r_util_reseed (struct ccnr_handle * h)
Definition at line 102 of file ccnr_util.c.
Referenced by r_init_create().
PUBLIC intmax_t r_util_segment_from_component (const unsigned char * ccnb, size_t start, size_t stop)
Definition at line 146 of file ccnr_util.c.
Referenced by r_proto_continue_enumeration(), r_proto_expect_content(), and r_proto_start_write().
PUBLIC int r_util_timecmp (long secA, unsigned usecA, long secB, unsigned usecB)
Definition at line 137 of file ccnr_util.c.
Referenced by reap_enumerations().