Content-Centric Networking in C: include/ccn/digest.h File Reference
digest.h File Reference
Message digest interface.
Enumerations
enum ccn_digest_id {
CCN_DIGEST_DEFAULT, CCN_DIGEST_SHA1, CCN_DIGEST_SHA224, CCN_DIGEST_SHA256,
CCN_DIGEST_SHA384, CCN_DIGEST_SHA512
}
Functions
struct ccn_digest * ccn_digest_create (enum ccn_digest_id)
void ccn_digest_destroy (struct ccn_digest **)
enum ccn_digest_id ccn_digest_getid (struct ccn_digest *)
size_t ccn_digest_size (struct ccn_digest *)
void ccn_digest_init (struct ccn_digest *)
int ccn_digest_update (struct ccn_digest *, const void *, size_t)
int ccn_digest_final (struct ccn_digest *, unsigned char *, size_t)
Detailed Description
Message digest interface.
This is a veneer so that the ccn code can use various underlying implementations of the message digest functions without muss and fuss.
Part of the CCNx C Library.
Copyright (C) 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file digest.h.
Enumeration Type Documentation
enum ccn_digest_id
Enumerator:
CCN_DIGEST_DEFAULT
CCN_DIGEST_SHA1
CCN_DIGEST_SHA224
CCN_DIGEST_SHA256
CCN_DIGEST_SHA384
CCN_DIGEST_SHA512
Definition at line 33 of file digest.h.
Function Documentation
struct ccn_digest* ccn_digest_create (enum ccn_digest_id) [read]
Definition at line 32 of file ccn_digest.c.
Referenced by ccn_aes_digest(), ccn_digest_Content(), ccn_digest_ContentObject(), ccn_locate_key(), ccns_slice_name(), main(), sendSlice(), and SyncAddRoot().
void ccn_digest_destroy (struct ccn_digest **)
Definition at line 54 of file ccn_digest.c.
Referenced by ccn_aes_keystore_file_init(), ccn_digest_Content(), ccn_digest_ContentObject(), ccn_locate_key(), ccns_slice_name(), sendSlice(), and SyncAddRoot().
int ccn_digest_final (struct ccn_digest * , unsigned char * , size_t)
Definition at line 92 of file ccn_digest.c.
Referenced by ccn_aes_digest(), ccn_digest_Content(), ccn_digest_ContentObject(), ccn_locate_key(), ccns_slice_name(), main(), sendSlice(), and SyncAddRoot().
enum ccn_digest_id ccn_digest_getid (struct ccn_digest *)
Definition at line 63 of file ccn_digest.c.
void ccn_digest_init (struct ccn_digest *)
Definition at line 75 of file ccn_digest.c.
Referenced by ccn_aes_digest(), ccn_digest_Content(), ccn_digest_ContentObject(), ccn_locate_key(), ccns_slice_name(), main(), sendSlice(), and SyncAddRoot().
size_t ccn_digest_size (struct ccn_digest *)
Definition at line 69 of file ccn_digest.c.
Referenced by ccn_locate_key(), ccns_slice_name(), main(), sendSlice(), and SyncAddRoot().
int ccn_digest_update (struct ccn_digest * , const void * , size_t)
Definition at line 82 of file ccn_digest.c.
Referenced by ccn_aes_digest(), ccn_digest_Content(), ccn_digest_ContentObject(), ccn_locate_key(), ccns_slice_name(), main(), sendSlice(), and SyncAddRoot().