Content-Centric Networking in C: lib/encodedecodetest.c File Reference
encodedecodetest.c File Reference
Unit tests for CCNx C library.
Functions
int encode_sample_test (const struct ccn_pkey *signing_key, const struct ccn_pkey *verification_key, const char *algorithm, char *paths[], char *contents[], struct ccn_charbuf *signed_info, char *outname)
struct path * path_create (char *strpath)
void path_destroy (struct path **path)
int encode_message (struct ccn_charbuf *message, struct path *name_path, char *data, size_t len, struct ccn_charbuf *signed_info, const void *pkey, const char *digest_algorithm)
int decode_message (struct ccn_charbuf *message, struct path *name_path, char *data, size_t len, const void *verkey)
int unit_tests_for_signing (struct ccn *h, int *ip, int symmetric)
int expected_res (int res, char code)
static void init_all_chars_percent_encoded (void)
static void init_all_chars_mixed_encoded (void)
int main (int argc, char *argv[])
Variables
static char all_chars_percent_encoded [256 *3+1]
static char all_chars_mixed_encoded [256 *2+2]
static const char * all_chars_percent_encoded_canon = "%F0%F1%F2%F3%F4%F5%F6%F7%F8%F9%FA%FB%FC%FD%FE%FF"
Detailed Description
Unit tests for CCNx C library.
A CCNx program.
Copyright (C) 2009-2013 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file encodedecodetest.c.
Function Documentation
int decode_message (struct ccn_charbuf * message, struct path * name_path, char * data, size_t len, const void * verkey)
Definition at line 99 of file encodedecodetest.c.
Referenced by encode_sample_test(), and main().
int encode_message (struct ccn_charbuf * message, struct path * name_path, char * data, size_t len, struct ccn_charbuf * signed_info, const void * pkey, const char * digest_algorithm)
Definition at line 72 of file encodedecodetest.c.
Referenced by encode_sample_test(), and main().
int encode_sample_test (const struct ccn_pkey * signing_key, const struct ccn_pkey * verification_key, const char * algorithm, char * paths[], char * contents[], struct ccn_charbuf * signed_info, char * outname)
Definition at line 819 of file encodedecodetest.c.
Referenced by main().
int expected_res (int res, char code)
Definition at line 220 of file encodedecodetest.c.
Referenced by main().
static void init_all_chars_mixed_encoded (void) [static]
Definition at line 250 of file encodedecodetest.c.
Referenced by main().
static void init_all_chars_percent_encoded (void) [static]
Definition at line 237 of file encodedecodetest.c.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 282 of file encodedecodetest.c.
struct path* path_create (char * strpath) [read]
Definition at line 45 of file encodedecodetest.c.
Referenced by encode_sample_test(), and main().
void path_destroy (struct path ** path)
Definition at line 66 of file encodedecodetest.c.
Referenced by encode_sample_test(), and main().
int unit_tests_for_signing (struct ccn * h, int * ip, int symmetric)
Definition at line 151 of file encodedecodetest.c.
Referenced by main().
Variable Documentation
char all_chars_mixed_encoded[256 *2+2] [static]
Definition at line 235 of file encodedecodetest.c.
Referenced by init_all_chars_mixed_encoded().
char all_chars_percent_encoded[256 *3+1] [static]
Definition at line 234 of file encodedecodetest.c.
Referenced by init_all_chars_percent_encoded(), and main().
const char* all_chars_percent_encoded_canon = "%F0%F1%F2%F3%F4%F5%F6%F7%F8%F9%FA%FB%FC%FD%FE%FF" [static]
Definition at line 264 of file encodedecodetest.c.
Referenced by main().