Content-Centric Networking in C: include/ccn/keystore.h File Reference
keystore.h File Reference
KEYSTORE interface.
Data Structures
struct keystore_header_st
Defines
#define CCN_SECRET_KEY_LENGTH 256 /* We only support HMAC-SHA256 right now */
Typedefs
typedef struct keystore_header_st keystore_header
Functions
struct ccn_keystore * ccn_keystore_create (void)
void ccn_keystore_destroy (struct ccn_keystore **p)
int ccn_keystore_init (struct ccn_keystore *p, char *name, char *password)
struct ccn_pkey * ccn_keystore_key (struct ccn_keystore *p)
struct ccn_pkey * ccn_keystore_public_key (struct ccn_keystore *p)
const char * ccn_keystore_digest_algorithm (struct ccn_keystore *p)
ssize_t ccn_keystore_key_digest_length (struct ccn_keystore *p)
const unsigned char * ccn_keystore_key_digest (struct ccn_keystore *p)
struct ccn_certificate * ccn_keystore_certificate (struct ccn_keystore *p)
int ccn_keystore_file_init (char *filename, char *password, char *subject, int keylength, int validity_days)
Create a PKCS12 keystore file.
struct ccn_keystore * ccn_aes_keystore_create (void)
int ccn_aes_keystore_init (struct ccn_keystore *p, char *filename, const char *password)
int ccn_aes_keystore_file_init (char *filename, const char *password, unsigned char *key, int keylength)
Create an AES keystore file.
void ccn_create_filename_with_digest_suffix (struct ccn_charbuf *filename, const unsigned char *key, int keylength)
void ccn_create_aes_filename_from_digest (struct ccn_charbuf *filename, const unsigned char *digest, int digest_len)
int ccn_create_aes_filename_from_key (struct ccn_charbuf *filename, unsigned char *key, int keylength)
void ccn_generate_symmetric_key (unsigned char *keybuf, int keylength)
struct ccn_charbuf * ccn_get_aes_keystore_path (struct ccn *h, char *suffix)
struct ccn_pkey * ccn_keystore_private_key (struct ccn_keystore *p) DEPRECATED
Deprecated in favor of ccn_keystore_key.
ssize_t ccn_keystore_public_key_digest_length (struct ccn_keystore *p) DEPRECATED
Deprecated in favor of ccn_keystore_digest_length.
const unsigned char * ccn_keystore_public_key_digest (struct ccn_keystore *p) DEPRECATED
Deprecated in favor of ccn_keystore_key_digest.
Detailed Description
KEYSTORE interface.
This is a veneer so that the ccn code can avoid exposure to the underlying keystore implementation types.
Part of the CCNx C Library.
Copyright (C) 2009,2013 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file keystore.h.
Define Documentation
#define CCN_SECRET_KEY_LENGTH 256 /* We only support HMAC-SHA256 right now */
Definition at line 32 of file keystore.h.
Referenced by main().
Typedef Documentation
typedef struct keystore_header_st keystore_header
Function Documentation
struct ccn_keystore* ccn_aes_keystore_create (void) [read]
Definition at line 90 of file ccn_aes_keystore.c.
Referenced by ccn_load_signing_key(), ccn_locate_key(), and main().
int ccn_aes_keystore_file_init (char * filename, const char * password, unsigned char * key, int keylength)
Create an AES keystore file.
Parameters:
filename the name of the keystore file to be created.
password the import/export password for the keystore.
key the key to encrypt in the keystore
Returns:
0 on success, -1 on failure
Definition at line 203 of file ccn_aes_keystore.c.
Referenced by main().
int ccn_aes_keystore_init (struct ccn_keystore * p, char * filename, const char * password)
Definition at line 117 of file ccn_aes_keystore.c.
Referenced by ccn_load_signing_key(), ccn_locate_key(), and main().
void ccn_create_aes_filename_from_digest (struct ccn_charbuf * filename, const unsigned char * digest, int digest_len)
int ccn_create_aes_filename_from_key (struct ccn_charbuf * filename, unsigned char * key, int keylength)
Definition at line 293 of file ccn_aes_keystore.c.
Referenced by main().
void ccn_create_filename_with_digest_suffix (struct ccn_charbuf * filename, const unsigned char * key, int keylength)
Definition at line 306 of file ccn_aes_keystore.c.
Referenced by ccn_create_aes_filename_from_key(), and ccn_locate_key().
void ccn_generate_symmetric_key (unsigned char * keybuf, int keylength)
Definition at line 283 of file ccn_aes_keystore.c.
Referenced by main().
struct ccn_charbuf* ccn_get_aes_keystore_path (struct ccn * h, char * suffix) [read]
struct ccn_certificate* ccn_keystore_certificate (struct ccn_keystore * p) [read]
Definition at line 202 of file ccn_keystore.c.
struct ccn_keystore* ccn_keystore_create (void) [read]
Definition at line 88 of file ccn_keystore.c.
Referenced by ccn_load_signing_key(), and main().
void ccn_keystore_destroy (struct ccn_keystore ** p)
Definition at line 100 of file ccn_keystore.c.
Referenced by ccn_load_signing_key(), ccn_locate_key(), and finalize_keystore().
const char* ccn_keystore_digest_algorithm (struct ccn_keystore * p)
Definition at line 180 of file ccn_keystore.c.
Referenced by ccn_sign_content(), and main().
int ccn_keystore_file_init (char * filename, char * password, char * subject, int keylength, int validity_days)
Create a PKCS12 keystore file.
Parameters:
filename the name of the keystore file to be created.
password the import/export password for the keystore.
subject the subject (and issuer) name in the certificate.
keylength the number of bits in the RSA key to be generated. A value <= 0 will result in the default (1024) being used.
validity_days the number of days the certificate in the keystore will be valid. A value <= 0 will result in the default (30) being used.
Returns:
0 on success, -1 on failure
Definition at line 249 of file ccn_keystore.c.
Referenced by ccn_load_or_create_key(), ccnd_init_internal_keystore(), ccnr_init_repo_keystore(), and main().
int ccn_keystore_init (struct ccn_keystore * p, char * name, char * password)
Definition at line 108 of file ccn_keystore.c.
Referenced by ccn_load_signing_key(), and main().
struct ccn_pkey* ccn_keystore_key (struct ccn_keystore * p) [read]
Definition at line 162 of file ccn_keystore.c.
Referenced by ccn_keystore_private_key(), ccn_locate_key(), ccn_sign_content(), and main().
const unsigned char* ccn_keystore_key_digest (struct ccn_keystore * p)
Definition at line 194 of file ccn_keystore.c.
Referenced by ccn_get_public_key(), ccn_keystore_public_key_digest(), ccn_load_signing_key(), ccn_sign_content(), and main().
ssize_t ccn_keystore_key_digest_length (struct ccn_keystore * p)
Definition at line 188 of file ccn_keystore.c.
Referenced by ccn_get_public_key(), ccn_keystore_public_key_digest_length(), ccn_load_signing_key(), ccn_sign_content(), and main().
struct ccn_pkey* ccn_keystore_private_key (struct ccn_keystore * p) [read]
Deprecated in favor of ccn_keystore_key.
Definition at line 399 of file ccn_keystore.c.
struct ccn_pkey* ccn_keystore_public_key (struct ccn_keystore * p) [read]
Definition at line 171 of file ccn_keystore.c.
Referenced by ccn_get_public_key(), ccn_sign_content(), and main().
const unsigned char* ccn_keystore_public_key_digest (struct ccn_keystore * p)
Deprecated in favor of ccn_keystore_key_digest.
Definition at line 416 of file ccn_keystore.c.
ssize_t ccn_keystore_public_key_digest_length (struct ccn_keystore * p)
Deprecated in favor of ccn_keystore_digest_length.
Definition at line 407 of file ccn_keystore.c.