Content-Centric Networking in C: include/ccn/openssl_ex.h File Reference
openssl_ex.h File Reference
OpenSSL extension interface.
Defines
#define EVP_PKEY_HMAC NID_hmac
#define NEED_OPENSSL_1_0_COMPAT
Functions
void * EVP_PKEY_get0 (EVP_PKEY *pkey)
EVP_PKEY * EVP_PKEY_new_mac_key (int type, ENGINE *e, const unsigned char *key, int keylen)
int ccn_PKEY_assign (EVP_PKEY *pkey, int type, char *key)
Detailed Description
OpenSSL extension interface.
Used to define our own OpenSSL 1.0.X extensions that will go away when we switch to OpenSSL 1.0.X
Part of the CCNx C Library.
Copyright (C) 2013 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file openssl_ex.h.
Define Documentation
#define EVP_PKEY_HMAC NID_hmac
Definition at line 32 of file openssl_ex.h.
Referenced by ccn_aes_keystore_init(), and ccn_sigc_signature_max_size().
#define NEED_OPENSSL_1_0_COMPAT
Definition at line 33 of file openssl_ex.h.
Function Documentation
int ccn_PKEY_assign (EVP_PKEY * pkey, int type, char * key)
Referenced by ccn_aes_keystore_init().
void* EVP_PKEY_get0 (EVP_PKEY * pkey)
Referenced by ccn_sigc_init(), ccn_verify_signature(), and main().
EVP_PKEY* EVP_PKEY_new_mac_key (int type, ENGINE * e, const unsigned char * key, int keylen)