Content-Centric Networking in C: include/ccn/random.h File Reference
random.h File Reference
Pseudo-random number generation.
Functions
void ccn_random_bytes (unsigned char *buf, size_t size)
Generate pseudo-random bytes.
void ccn_add_entropy (const void *buf, size_t size, int bits_of_entropy)
Feed some entropy to the random number generator.
Detailed Description
Pseudo-random number generation.
Part of the CCNx C Library.
Copyright (C) 2010 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file random.h.
Function Documentation
void ccn_add_entropy (const void * buf, size_t size, int bits_of_entropy)
Feed some entropy to the random number generator.
Parameters:
buf is the source buffer
size is in bytes
bits_of_entropy is an estimate; use 0 to make me guess
Definition at line 607 of file ccn_signing.c.
Referenced by main().
void ccn_random_bytes (unsigned char * buf, size_t size)
Generate pseudo-random bytes.
Parameters:
buf is the destination buffer
size is in bytes
Definition at line 590 of file ccn_signing.c.
Referenced by ccn_name_append_nonce(), and main().