Content-Centric Networking in C: include/ccn/signing.h File Reference
signing.h File Reference
Message signing interface.
Functions
struct ccn_sigc * ccn_sigc_create (void)
int ccn_sigc_init (struct ccn_sigc *ctx, const char *digest, const struct ccn_pkey *priv_key)
void ccn_sigc_destroy (struct ccn_sigc **)
int ccn_sigc_update (struct ccn_sigc *ctx, const void *data, size_t size)
int ccn_sigc_final (struct ccn_sigc *ctx, struct ccn_signature *signature, size_t *size, const struct ccn_pkey *priv_key)
size_t ccn_sigc_signature_max_size (struct ccn_sigc *ctx, const struct ccn_pkey *priv_key)
int ccn_verify_signature (const unsigned char *msg, size_t size, const struct ccn_parsed_ContentObject *co, const struct ccn_pkey *verification_pubkey)
struct ccn_pkey * ccn_d2i_pubkey (const unsigned char *p, size_t size)
void ccn_pubkey_free (struct ccn_pkey *i_pubkey)
size_t ccn_pubkey_size (const struct ccn_pkey *i_pubkey)
int ccn_append_pubkey_blob (struct ccn_charbuf *c, const struct ccn_pkey *i_pubkey)
Detailed Description
Message signing interface.
This is a veneer so that the ccn code can use various underlying implementations of the signature functions without muss and fuss.
Part of the CCNx C Library.
Copyright (C) 2008, 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file signing.h.
Function Documentation
int ccn_append_pubkey_blob (struct ccn_charbuf * c, const struct ccn_pkey * i_pubkey)
Definition at line 559 of file ccn_signing.c.
Referenced by ccn_get_public_key(), ccn_sign_content(), and main().
struct ccn_pkey* ccn_d2i_pubkey (const unsigned char * p, size_t size) [read]
Definition at line 534 of file ccn_signing.c.
Referenced by ccn_cache_key(), and ccn_locate_key().
void ccn_pubkey_free (struct ccn_pkey * i_pubkey)
Definition at line 543 of file ccn_signing.c.
Referenced by finalize_pkey().
size_t ccn_pubkey_size (const struct ccn_pkey * i_pubkey)
Definition at line 550 of file ccn_signing.c.
struct ccn_sigc* ccn_sigc_create (void) [read]
Definition at line 250 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject(), and ccn_verify_signature().
void ccn_sigc_destroy (struct ccn_sigc **)
Definition at line 256 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject(), and ccn_verify_signature().
int ccn_sigc_final (struct ccn_sigc * ctx, struct ccn_signature * signature, size_t * size, const struct ccn_pkey * priv_key)
Definition at line 286 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject().
int ccn_sigc_init (struct ccn_sigc * ctx, const char * digest, const struct ccn_pkey * priv_key)
Definition at line 267 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject().
size_t ccn_sigc_signature_max_size (struct ccn_sigc * ctx, const struct ccn_pkey * priv_key)
Definition at line 297 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject().
int ccn_sigc_update (struct ccn_sigc * ctx, const void * data, size_t size)
Definition at line 278 of file ccn_signing.c.
Referenced by ccn_encode_ContentObject().
int ccn_verify_signature (const unsigned char * msg, size_t size, const struct ccn_parsed_ContentObject * co, const struct ccn_pkey * verification_pubkey)
Definition at line 388 of file ccn_signing.c.
Referenced by ccn_dispatch_message(), ccn_verify_content(), decode_message(), and main().