Content-Centric Networking in C: include/ccn/strategy_mgmt.h File Reference
strategy_mgmt.h File Reference
Data Structures
struct ccn_strategy_selection
Provide marshalling and unmarshalling for strategy selection requests and responses.
Functions
struct ccn_strategy_selection * ccn_strategy_selection_parse (const unsigned char *p, size_t size)
Validate and parse an encoded strategy selection message.
int ccnb_append_strategy_selection (struct ccn_charbuf *c, const struct ccn_strategy_selection *ss)
Encode a strategy selection message.
void ccn_strategy_selection_destroy (struct ccn_strategy_selection **pss)
Release resources allocated by decoder.
Detailed Description
Definition in file strategy_mgmt.h.
Function Documentation
void ccn_strategy_selection_destroy (struct ccn_strategy_selection ** pss)
Release resources allocated by decoder.
Definition at line 105 of file ccn_strategy_mgmt.c.
Referenced by ccn_strategy_selection_parse(), ccnd_req_strategy(), ccndc_do_strategy_action(), ccndc_strategy(), main(), and parse_ccn_strategy_selection().
struct ccn_strategy_selection* ccn_strategy_selection_parse (const unsigned char * p, size_t size) [read]
Validate and parse an encoded strategy selection message.
Definition at line 32 of file ccn_strategy_mgmt.c.
Referenced by ccnd_req_strategy(), ccndc_do_strategy_action(), and main().
int ccnb_append_strategy_selection (struct ccn_charbuf * c, const struct ccn_strategy_selection * ss)
Encode a strategy selection message.
Definition at line 116 of file ccn_strategy_mgmt.c.
Referenced by ccnd_req_strategy(), ccndc_do_strategy_action(), and main().