Content-Centric Networking in C: sync_diff_add_closure Struct Reference
sync_diff_add_closure Struct Reference
sync_diff_add_closure is called from the differencing operation to note a name difference for sdd.
Data Fields
int(* add)(struct sync_diff_add_closure *ac, struct ccn_charbuf *name)
struct sync_diff_data * diff_data
void * data
Detailed Description
sync_diff_add_closure is called from the differencing operation to note a name difference for sdd.
If name == NULL then there are no more names to be produced, and there should be no future references to sdd. The data is private to the closure, and the client owns all storage in the closure, except for sync_diff_data.
Definition at line 44 of file sync_diff.h.
Field Documentation
int(* sync_diff_add_closure::add)(struct sync_diff_add_closure *ac, struct ccn_charbuf *name)
Definition at line 45 of file sync_diff.h.
Referenced by abortCompare(), addNameFromCompare(), ccns_open(), and compareAction().
void* sync_diff_add_closure::data
Definition at line 48 of file sync_diff.h.
Referenced by ccns_open().
struct sync_diff_data* sync_diff_add_closure::diff_data
Definition at line 47 of file sync_diff.h.
Referenced by ccns_open(), and my_add().
The documentation for this struct was generated from the following file:
sync/sync_diff.h