Content-Centric Networking in C: sync/sync_diff.c File Reference
sync_diff.c File Reference
Part of CCNx Sync.
Functions
static void setCovered (struct SyncHashCacheEntry *ce)
static int isCovered (struct SyncHashCacheEntry *ce)
static struct
sync_diff_fetch_data * allocNodeFetch (struct sync_diff_data *sdd, struct SyncHashCacheEntry *ce)
static struct
sync_diff_fetch_data * addNodeFetch (struct sync_diff_data *sdd, struct SyncHashCacheEntry *ce, enum sync_diff_side side)
static struct
sync_diff_fetch_data * remNodeFetch (struct sync_diff_data *sdd, struct SyncHashCacheEntry *ce)
static int formatCacheEntry (struct SyncRootStruct *root, char *dst, int lim, char *prefix, struct SyncHashCacheEntry *ce)
static void showCacheEntry1 (struct SyncRootStruct *root, char *here, char *msg, struct SyncHashCacheEntry *ce)
static void showCacheEntry2 (struct SyncRootStruct *root, char *here, char *msg, struct SyncHashCacheEntry *ce1, struct SyncHashCacheEntry *ce2)
static int compareAction (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
static int updateAction (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
static void freeFetchData (struct sync_diff_fetch_data *fd)
static void resetDiffData (struct sync_diff_data *sdd)
static void resetUpdateData (struct sync_update_data *ud)
static int abortCompare (struct sync_diff_data *sdd, char *why)
static int comparisonFailed (struct sync_diff_data *sdd, char *why, int line)
static int extractBuf (struct ccn_charbuf *cb, struct SyncNodeComposite *nc, struct SyncNodeElem *ne)
static struct SyncHashCacheEntry * entryForHash (struct SyncRootStruct *root, struct ccn_charbuf *hash)
static void initWorkerFromHash (struct SyncRootStruct *root, struct SyncTreeWorkerHead *tw, struct ccn_charbuf *hash)
static struct SyncHashCacheEntry * cacheEntryForElem (struct sync_diff_data *sdd, struct SyncNodeComposite *nc, struct SyncNodeElem *ne)
static void kickCompare (struct sync_diff_data *sdd, int micros)
static void kickUpdate (struct sync_update_data *ud, int micros)
static struct ccn_charbuf * constructCommandPrefix (struct SyncRootStruct *root, struct ccn_charbuf *hash, char *cmd)
static int start_node_fetch (struct sync_diff_data *sdd, struct SyncHashCacheEntry *ce, enum sync_diff_side side)
static int doPreload (struct sync_diff_data *sdd, struct SyncTreeWorkerHead *twHead, enum sync_diff_side side)
doPreload(sdd) walks the given tree, and requests a fetch for every node that is not covered and is not in the cache, and is not being fetched.
static int addNameFromCompare (struct sync_diff_data *sdd)
static int doComparison (struct sync_diff_data *sdd)
static struct SyncHashCacheEntry * newNodeCommon (struct SyncRootStruct *root, struct SyncNodeAccum *nodes, struct SyncNodeComposite *nc)
static struct SyncHashCacheEntry * node_from_nodes (struct SyncRootStruct *root, struct SyncNodeAccum *na)
static int node_from_names (struct sync_update_data *ud, int split)
static int try_node_split (struct sync_update_data *ud)
static int add_update_name (struct sync_update_data *ud, struct ccn_charbuf *name, int isNew)
static int merge_names (struct sync_update_data *ud)
static int updateError (struct sync_update_data *ud)
int sync_diff_start (struct sync_diff_data *sdd)
sync_diff_start starts a differencing operation between two sync trees, specified by sdd->hashX and sdd->hashY for the collection in sdd->root.
int sync_diff_note_node (struct sync_diff_data *sdd, struct SyncHashCacheEntry *ce)
sync_diff_note_node is used to establish the result of the client closure sdd->get, and restarts the comparison.
int sync_diff_stop (struct sync_diff_data *sdd)
sync_diff_stop will stop the differencing operation if it has not completed.
int sync_update_start (struct sync_update_data *ud, struct SyncNameAccum *acc)
sync_update_start is called to start an update of ud->ceStart, based on the names added via acc, to result in a tree with root hash stored in ud->ceStop.
int sync_update_stop (struct sync_update_data *ud)
sync_update_stop can be called to stop the update operation.
Variables
static int nodeSplitTrigger = 4000
static int hashSplitTrigger = 17
static int shortDelayMicros = 1000
static int namesYieldInc = 100
static int namesYieldMicros = 20*1000
Detailed Description
Part of CCNx Sync.
Copyright (C) 2012-2013 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file sync_diff.c.
Function Documentation
static int abortCompare (struct sync_diff_data * sdd, char * why) [static]
Definition at line 215 of file sync_diff.c.
Referenced by compareAction(), and doPreload().
static int add_update_name (struct sync_update_data * ud, struct ccn_charbuf * name, int isNew) [static]
Definition at line 1232 of file sync_diff.c.
Referenced by merge_names().
static int addNameFromCompare (struct sync_diff_data * sdd) [static]
Definition at line 542 of file sync_diff.c.
Referenced by doComparison().
static struct sync_diff_fetch_data* addNodeFetch (struct sync_diff_data * sdd, struct SyncHashCacheEntry * ce, enum sync_diff_side side) [static, read]
Definition at line 78 of file sync_diff.c.
Referenced by start_node_fetch().
static struct sync_diff_fetch_data* allocNodeFetch (struct sync_diff_data * sdd, struct SyncHashCacheEntry * ce) [static, read]
Definition at line 66 of file sync_diff.c.
Referenced by addNodeFetch().
static struct SyncHashCacheEntry* cacheEntryForElem (struct sync_diff_data * sdd, struct SyncNodeComposite * nc, struct SyncNodeElem * ne) [static, read]
Definition at line 266 of file sync_diff.c.
Referenced by doComparison(), and doPreload().
static int compareAction (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 829 of file sync_diff.c.
Referenced by kickCompare().
static int comparisonFailed (struct sync_diff_data * sdd, char * why, int line) [static]
Definition at line 235 of file sync_diff.c.
Referenced by doComparison().
static struct ccn_charbuf* constructCommandPrefix (struct SyncRootStruct * root, struct ccn_charbuf * hash, char * cmd) [static, read]
Definition at line 341 of file sync_diff.c.
Referenced by start_node_fetch().
static int doComparison (struct sync_diff_data * sdd) [static]
Definition at line 575 of file sync_diff.c.
Referenced by compareAction().
static int doPreload (struct sync_diff_data * sdd, struct SyncTreeWorkerHead * twHead, enum sync_diff_side side) [static]
doPreload(sdd) walks the given tree, and requests a fetch for every node that is not covered and is not in the cache, and is not being fetched.
This allows sync trees to be fetched in parallel.
Returns:
< 0 for failure, 0 for incomplete, and > 0 for success
Definition at line 451 of file sync_diff.c.
Referenced by compareAction().
static struct SyncHashCacheEntry* entryForHash (struct SyncRootStruct * root, struct ccn_charbuf * hash) [static, read]
Definition at line 250 of file sync_diff.c.
Referenced by compareAction(), initWorkerFromHash(), newNodeCommon(), node_from_nodes(), and sync_diff_start().
static int extractBuf (struct ccn_charbuf * cb, struct SyncNodeComposite * nc, struct SyncNodeElem * ne) [static]
Definition at line 241 of file sync_diff.c.
Referenced by doComparison(), and merge_names().
static int formatCacheEntry (struct SyncRootStruct * root, char * dst, int lim, char * prefix, struct SyncHashCacheEntry * ce) [static]
Definition at line 126 of file sync_diff.c.
Referenced by showCacheEntry1(), and showCacheEntry2().
static void freeFetchData (struct sync_diff_fetch_data * fd) [static]
Definition at line 165 of file sync_diff.c.
Referenced by doPreload(), resetDiffData(), start_node_fetch(), and sync_diff_note_node().
static void initWorkerFromHash (struct SyncRootStruct * root, struct SyncTreeWorkerHead * tw, struct ccn_charbuf * hash) [static]
Definition at line 258 of file sync_diff.c.
Referenced by compareAction().
static int isCovered (struct SyncHashCacheEntry * ce) [static]
Definition at line 56 of file sync_diff.c.
Referenced by doComparison().
static void kickCompare (struct sync_diff_data * sdd, int micros) [static]
Definition at line 305 of file sync_diff.c.
Referenced by sync_diff_note_node(), and sync_diff_start().
static void kickUpdate (struct sync_update_data * ud, int micros) [static]
Definition at line 323 of file sync_diff.c.
Referenced by sync_update_start().
static int merge_names (struct sync_update_data * ud) [static]
Definition at line 1258 of file sync_diff.c.
Referenced by updateAction().
static struct SyncHashCacheEntry* newNodeCommon (struct SyncRootStruct * root, struct SyncNodeAccum * nodes, struct SyncNodeComposite * nc) [static, read]
Definition at line 955 of file sync_diff.c.
Referenced by node_from_names(), and node_from_nodes().
static int node_from_names (struct sync_update_data * ud, int split) [static]
Definition at line 1079 of file sync_diff.c.
Referenced by try_node_split(), and updateAction().
static struct SyncHashCacheEntry* node_from_nodes (struct SyncRootStruct * root, struct SyncNodeAccum * na) [static, read]
Definition at line 1020 of file sync_diff.c.
Referenced by updateAction().
static struct sync_diff_fetch_data* remNodeFetch (struct sync_diff_data * sdd, struct SyncHashCacheEntry * ce) [static, read]
Definition at line 105 of file sync_diff.c.
Referenced by start_node_fetch(), and sync_diff_note_node().
static void resetDiffData (struct sync_diff_data * sdd) [static]
Definition at line 175 of file sync_diff.c.
Referenced by abortCompare(), compareAction(), sync_diff_start(), and sync_diff_stop().
static void resetUpdateData (struct sync_update_data * ud) [static]
Definition at line 198 of file sync_diff.c.
Referenced by sync_update_start(), and sync_update_stop().
static void setCovered (struct SyncHashCacheEntry * ce) [static]
Definition at line 46 of file sync_diff.c.
Referenced by doComparison(), isCovered(), and newNodeCommon().
static void showCacheEntry1 (struct SyncRootStruct * root, char * here, char * msg, struct SyncHashCacheEntry * ce) [static]
Definition at line 135 of file sync_diff.c.
Referenced by updateAction().
static void showCacheEntry2 (struct SyncRootStruct * root, char * here, char * msg, struct SyncHashCacheEntry * ce1, struct SyncHashCacheEntry * ce2) [static]
Definition at line 143 of file sync_diff.c.
Referenced by compareAction(), and updateAction().
static int start_node_fetch (struct sync_diff_data * sdd, struct SyncHashCacheEntry * ce, enum sync_diff_side side) [static]
Definition at line 375 of file sync_diff.c.
Referenced by doComparison(), and doPreload().
int sync_diff_note_node (struct sync_diff_data * sdd, struct SyncHashCacheEntry * ce)
sync_diff_note_node is used to establish the result of the client closure sdd->get, and restarts the comparison.
When the client closure sdd->get is called it should initiate the fetch or construction of a sync tree node. Depending on characteristics of the client the sync tree node should be stored into either ce->ncL or ce->ncR, and sync_diff_note_node should be called. The flags in ce will be updated by sync_diff_note_node.
Returns:
< 0 for failure, no fetch queued for ce.
0 for no action, ce == NULL || ce has no node.
> 0 for success, fetch was queued and ce has a node.
Definition at line 1551 of file sync_diff.c.
Referenced by my_response().
int sync_diff_start (struct sync_diff_data * sdd)
sync_diff_start starts a differencing operation between two sync trees, specified by sdd->hashX and sdd->hashY for the collection in sdd->root.
If sdd->hashX is not empty then there must be a valid cache entry for it. If sdd->hashY is not empty then there must be a valid cache entry for it. The root (in sdd->root) must be valid, and have a valid base and scheduler. The client always owns the storage for sdd.
The closure sdd->get is called when a sync tree node is needed to continue the comparison, giving the name of the node (which has the hash as the last component). When the node has been fetched, the client should call sync_diff_note_node, which will continue the comparison.
The closure sdd->add is called once for each name that is covered by hashY but not by hashX. When there are no more additions then it is called once with name == NULL. The sdd->add closure is called with a name that may not be valid after the call completes, so the client must copy the name if it needs to persist.
Hint: If sdd->hashX is the empty hash (NULL or length == 0), then the differencing operation is simply an enumeration operation.
Returns:
< 0 for failure, 0 if no difference running, > 0 for success.
Definition at line 1519 of file sync_diff.c.
Referenced by each_round().
int sync_diff_stop (struct sync_diff_data * sdd)
sync_diff_stop will stop the differencing operation if it has not completed.
A call to sdd->add will NOT take place from within this call. Internal resources are released.
Returns:
< 0 for failure, 0 if already stopped, > 0 for success.
Definition at line 1609 of file sync_diff.c.
Referenced by ccns_close().
int sync_update_start (struct sync_update_data * ud, struct SyncNameAccum * acc)
sync_update_start is called to start an update of ud->ceStart, based on the names added via acc, to result in a tree with root hash stored in ud->ceStop.
Returns:
< 0 for failure, 0 if update already running, > 0 for success.
Definition at line 1623 of file sync_diff.c.
Referenced by each_round().
int sync_update_stop (struct sync_update_data * ud)
sync_update_stop can be called to stop the update operation.
Internal resources are released.
Returns:
< 0 for failure, 0 if no update running, > 0 for success.
Definition at line 1665 of file sync_diff.c.
Referenced by ccns_close().
static int try_node_split (struct sync_update_data * ud) [static]
Definition at line 1154 of file sync_diff.c.
Referenced by add_update_name().
static int updateAction (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 1375 of file sync_diff.c.
Referenced by kickUpdate().
static int updateError (struct sync_update_data * ud) [static]
Definition at line 1362 of file sync_diff.c.
Referenced by updateAction().
Variable Documentation
int hashSplitTrigger = 17 [static]
Definition at line 40 of file sync_diff.c.
Referenced by try_node_split().
int namesYieldInc = 100 [static]
Definition at line 42 of file sync_diff.c.
Referenced by merge_names().
int namesYieldMicros = 20*1000 [static]
Definition at line 43 of file sync_diff.c.
Referenced by merge_names().
int nodeSplitTrigger = 4000 [static]
Definition at line 39 of file sync_diff.c.
Referenced by add_update_name(), newNodeCommon(), node_from_nodes(), and try_node_split().
int shortDelayMicros = 1000 [static]
Definition at line 41 of file sync_diff.c.
Referenced by updateAction().