Content-Centric Networking in C: libexec/udplink.c File Reference
udplink.c File Reference
A CCNx link adaptor for UDP.
Defines
#define AI_ADDRCONFIG 0 /*IEEE Std 1003.1-2001/Cor 1-2002, item XSH/TC1/D6/20*/
Functions
void udplink_fatal (int line, char *format,...)
void usage (char *name)
void udplink_note (char *format,...)
void udplink_print_data (char *source, unsigned char *data, int start, int length, int logging)
ssize_t send_remote_unencapsulated (int s, struct addrinfo *r, unsigned char *buf, size_t start, size_t length)
void process_options (int argc, char *const argv[], struct options *opt)
void set_multicast_sockopt (int socket_r, int socket_w, struct addrinfo *ai, struct options *opt)
void changeloglevel (int s)
int main (int argc, char *const argv[])
Variables
static struct options options
Detailed Description
A CCNx link adaptor for UDP.
Note:
Normally ccnd handles UDP directly, so this module is not used.
A CCNx program.
Copyright (C) 2008-2013 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file udplink.c.
Define Documentation
#define AI_ADDRCONFIG 0 /*IEEE Std 1003.1-2001/Cor 1-2002, item XSH/TC1/D6/20*/
Definition at line 43 of file udplink.c.
Referenced by main().
Function Documentation
void changeloglevel (int s)
Definition at line 319 of file udplink.c.
Referenced by main().
int main (int argc, char *const argv[])
Definition at line 334 of file udplink.c.
void process_options (int argc, char *const argv[], struct options * opt)
Definition at line 137 of file udplink.c.
Referenced by main().
ssize_t send_remote_unencapsulated (int s, struct addrinfo * r, unsigned char * buf, size_t start, size_t length)
Definition at line 126 of file udplink.c.
Referenced by main().
void set_multicast_sockopt (int socket_r, int socket_w, struct addrinfo * ai, struct options * opt)
Definition at line 246 of file udplink.c.
Referenced by main().
void udplink_fatal (int line, char * format, ...)
Definition at line 84 of file udplink.c.
Referenced by main(), process_options(), and set_multicast_sockopt().
void udplink_note (char * format, ...)
Definition at line 97 of file udplink.c.
Referenced by changeloglevel(), main(), process_options(), set_multicast_sockopt(), and udplink_print_data().
void udplink_print_data (char * source, unsigned char * data, int start, int length, int logging)
Definition at line 109 of file udplink.c.
Referenced by main().
void usage (char * name)
Definition at line 79 of file udplink.c.
Variable Documentation
struct options options [static]
Referenced by ccndc_strategy(), changeloglevel(), and main().